### ISSUE TITLE
Searching through items in a piece while on a page other than 1 will not show results

### ISSUE THREAD

**Issue by runyx** [punkave/apostrophe#1013]
When I am on the second page of items in a piece (in this example the second page of People) and try to search, I get back a page that says it has results but displays none. If I choose at the bottom to go to Page 1 they will display, so it seems like the Search feature does not bring you to the page 1 of search results.

![screen shot 2017-09-18 at 1 51 49 pm](https://user-images.githubusercontent.com/6238281/30556439-daf0b2ba-9c78-11e7-8bb2-3cdba79d97f8.png)

**Comment by boutell** [comment]
This got fixed.
