### ISSUE TITLE
Could not start the project

### ISSUE THREAD

**Issue by Mohsin05** [punkave/apostrophe#1021]
Hello, I hope the reader is fine. 
I am new to the nodejs. Actually,  I am trying to clone the repository to start the project. I am supposed to start the sample website like this : http://demo-cj7rv791e00cvr7gzenmgk2af.apostrophecms.org
For which I am cloning https://github.com/punkave/apostrophe/tree/master
Unfortunately,  There is no app.js file. 
I am sure, I am doing a blunder. 
Kindly help me out. 
Thank you.

**Comment by bobclewell** [comment]
Thanks for reaching out. 

The best way to get started with ApostropheCMS is reading through the tutorial here: http://apostrophecms.org/docs/tutorials/getting-started/index.html

That will walk you through setting up all the prerequisites for running Apostrophe, installing `apostrophe-cli`, creating a project, and then guide you through building your first project.
