### ISSUE TITLE
'apostrophe-templates': { viewsFolderFallback } not resolving paths if extension is not .html or .njk

### ISSUE THREAD

**Issue by mtthwmnc** [punkave/apostrophe#1036]
Assets included from the `views` directory do not properly resolve paths and end up throwing template errors

**Comment by boutell** [comment]
That works fine in my tests. Going to try with a .svg extension which was the bug report originally.

**Comment by boutell** [comment]
The bug is specific to non-.html, non-.njk extensions. Looking into it.

**Comment by boutell** [comment]
This was fixed.
