### ISSUE TITLE
Npm i error since 5.4.x

### ISSUE THREAD

**Issue by HollyPony** [punkave/apostrophe#1042]
Installing last version of npm, we get an installation error due to `i18n-node` dependency. I've pushed a merge request on it and there is an open issue : https://github.com/mashpie/i18n-node/issues/325.

Since it's an npm issue, regression, still unresolved, this issue is more a notice. Also, there is an open issue related to this bug on npm repo : https://github.com/npm/npm/issues/18417

**Comment by boutell** [comment]
I think I saw this too, I thought it was just me or the bad network connection I was on. Yikes.

**Comment by boutell** [comment]
I got into it with the npm team today, and they have already fixed it in 5.5.x. I added a warning about 5.4.x to our "creating your first project" page, with steps to install 5.3.x or 5.5.x.
