### ISSUE TITLE
#iOS #iPad: Menus do work fragile

### ISSUE THREAD

**Issue by neonsquare** [punkave/apostrophe#1061]
If I try to trigger a menu action e.g. in the page menu on the iPad, the action doesnt get triggered on touch. It seems I have to hold it for a short while and then tap again.

**Comment by boutell** [comment]
As with the other issue: we currently don't support multitouch/tablet editing in Apostrophe, which hasn't been on the to-do list for any of our clients so far, but we'd accept PRs in that direction as long as they don't unduly alter the experience for desktop/laptop users.

**Comment by boutell** [comment]
As with the other issue: we currently don't support multitouch/tablet editing in Apostrophe, which hasn't been on the to-do list for any of our clients so far, but we'd accept PRs in that direction as long as they don't unduly alter the experience for desktop/laptop users.

**Comment by neonsquare** [comment]
I might look into this. Any quick direction where the menu code currently lives?
Also: Is there a particular reason why the menu items only can get clicked after „activating“ them through hover? I personally would use hover just to signal clickability but make the item clickable even without getting hovered before.

**Comment by boutell** [comment]
@stuartromanek any guidance for @neonsquare on his offer to contribute around this?
