### ISSUE TITLE
running in docker.

### ISSUE THREAD

**Issue by JoshuaSeidel** [punkave/apostrophe#1071]
Based on the boilerplate. and latest version of apostrophe, when i do a node app.js i tget the following

npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.5.0
npm info lifecycle sr-apostrophe@1.0.0~prestart: sr-apostrophe@1.0.0
npm info lifecycle sr-apostrophe@1.0.0~start: sr-apostrophe@1.0.0

> sr-apostrophe@1.0.0 start /app
> node app.js

Error while constructing the apostrophe-utils module
Error: The module apostrophe-utils has an alias, utils, that conflicts with a module registered earlier or a core Apostrophe feature.
    at beforeConstruct (/app/node_modules/apostrophe/lib/modules/apostrophe-module/index.js:33:15)
    at beforeConstruct (/app/node_modules/moog/index.js:239:21)
    at /app/node_modules/moog/index.js:250:22
    at iterate (/app/node_modules/moog/node_modules/async/lib/async.js:146:13)
    at Immediate.<anonymous> (/app/node_modules/moog/node_modules/async/lib/async.js:157:25)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

npm info lifecycle sr-apostrophe@1.0.0~start: Failed to exec start script
npm ERR! Linux 4.9.49-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! sr-apostrophe@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sr-apostrophe@1.0.0 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sr-apostrophe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:

my app.js looks like

var apos = require('apostrophe')({
  shortName: 'apostrophe-boilerplate',
  title: 'Apostrophe Boilerplate',

  // See lib/modules for basic project-level configuration of our modules
  // responsible for serving static assets, managing page templates and
  // configuring user acounts.

  modules: {
   'apostrophe-attachments': {
    uploadfs: {
      backend: 's3',
      secret: '************',
      key: '*************',
      bucket: '*********-apostrophe-uploads',
      region: 'us-east-1'
    },
   'apostrophe-db': {
      uri: 'mongodb://mongo:27017/mydb'
    },
  }
  }
});

**Comment by boutell** [comment]
Hi Joshua,

I just tried these steps exactly:

```
npm install -g apostrophe-cli
apostrophe create-project seidel
node app
```

The site came up without errors.

I then tried replacing my app.js with the one you sent, and still received no errors.

I am not sure what is different about your environment but let me know if you can reproduce the issue following my steps.

**Comment by JoshuaSeidel** [comment]
@boutell 

i managed to get by it. it was a bunch of extra files in lib/modules

now its not picking up the right db, should be mongo as server name as in app.js but its trying to connect to 127.*

root@98f00cdce3c0:/app# cat app.js 
var apos = require('apostrophe')({
  shortName: 'sr-apostrophe',
  title: '********',

  // See lib/modules for basic project-level configuration of our modules
  // responsible for serving static assets, managing page templates and
  // configuring user acounts.

  modules: {
   'apostrophe-attachments': {
    uploadfs: {
      backend: 's3',
      secret: '*************',
      key: '***********',
      bucket: '********-apostrophe-uploads',
      region: 'us-east-1'
    },
   'apostrophe-db': {
      uri: 'mongodb://mongo:27017/mydb'
    },
  }
  }
});
root@98f00cdce3c0:/app# node app.js 
ERROR: There was an issue connecting to the database. Is it running?
Error while constructing the apostrophe-db module
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Connection.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)

**Comment by boutell** [comment]
Check your indentation, your configuration of apostrophe-db is nested inside your configuration of apostrophe-attachments.

Prettyprinted for clarity:

```
var apos = require('apostrophe')({
    shortName: 'seidel',
    title: 'seidel',

    // See lib/modules for basic project-level configuration of our modules
    // responsible for serving static assets, managing page templates and
    // configuring user acounts.

    modules: {
        'apostrophe-attachments': {
            uploadfs: {
                backend: 's3',
                secret: '',
                key: '',
                bucket: '********-apostrophe-uploads',
                region: 'us-east-1'
            },
            'apostrophe-db': {
                uri: 'mongodb://mongo:27017/mydb'
            },
        }
    }
});
```
