### ISSUE TITLE
Must be administrator to run apostrophe on Windows due to symbolic links in modules folder

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe#109]
Apostrophe creates symbolic links from public/modules to the public/ folders of individual modules registered via the asset mixin.

Most operating systems have no trouble with this, but Windows is a very special snowflake.

We're using an API that does work in Windows but only if you're an administrator.

The solution would be to copy the asset folders rather than symbolically linking them, if and only if we are on Windows. And possibly for everyone if we're in production, since that would make static asset delivery just a tiny bit faster on each request.

**Comment by benirose** [comment]
@boutell didn't you implement this? I remember seeing a message about the copy at startup for windows.

**Comment by boutell** [comment]
Yep
