### ISSUE TITLE
wysiwyg editor

### ISSUE THREAD

**Issue by JoshuaSeidel** [punkave/apostrophe#1095]
how do you enable the wysiwyg editor. I cant find any documentation online on how to do it. when editing a page i only get the rich text editor

**Comment by boutell** [comment]
Hi Joshua,

The rich text editor and the area editing features (click the "+" to add widgets like images, video, etc.) make up the Apostrophe WYSIWYG editing experience. Did you encounter documentation that led you to expect something different, or have experiences with the rich text editor that didn't feel WYSIWYG in a way you needed? Happy to discuss that.
