### ISSUE TITLE
Express 4?

### ISSUE THREAD

**Issue by israelidanny** [punkave/apostrophe#110]
Express 4 is out, and most of the sources I've heard from say it's pretty darn fast. 

Migration doesn't seem to be a pain:
https://github.com/visionmedia/express/wiki/Migrating-from-3.x-to-4.x
https://medium.com/javascript-and-the-server/aa6992b52bcd

**Comment by kylestetz** [comment]
Looping back around on this one to say that we're in the process of refactoring Apostrophe's backend (which will become the foundation for version 0.6) and it's built on the latest version of Express 4. More info on the sprints [here](https://groups.google.com/forum/#!topic/apostrophenow/RZoxUE6yLb4) and elsewhere on the [apostrophenow google group](https://groups.google.com/forum/#!forum/apostrophenow).

**Comment by israelidanny** [comment]
That's great :)

**Comment by benirose** [comment]
Tom and I just implemented Express 4 at the core of Apostrophe in the unstable branch (which will eventually become 0.6). That makes this ticket complete!
