### ISSUE TITLE
Wrong  import of bluebird module in /apostrophe-pages/lib/api.js

### ISSUE THREAD

**Issue by waqar-ai** [punkave/apostrophe#1132]
Bluebird module is named wrongly as "Bluebird" instead of "bluebird"  which breaks apostrophe code. 

[https://github.com/punkave/apostrophe/blob/8e4de31c3a7a3550d4e910c29e923a0bf4da3032/lib/modules/apostrophe-pages/lib/api.js](https://github.com/punkave/apostrophe/blob/8e4de31c3a7a3550d4e910c29e923a0bf4da3032/lib/modules/apostrophe-pages/lib/api.js)

**Comment by boutell** [comment]
This was fixed late last night, thanks.

**Comment by boutell** [comment]
(npm update)
