### ISSUE TITLE
Save to data.widget without object in addFields

### ISSUE THREAD

**Issue by RedHatter** [punkave/apostrophe#1148]
I'm attempting to create a layout widget with configuration options. I started by following the tutorial but ran into an issue. I would like to create a few areas that can be edited directly on page but not from the edit modal. 

I tried simply remove the configuration for the areas from the addFields (as shown below) but now the areas don't save any content. I assume new properties can't be added to `data.widget` unless there in addFields?

index.js

    module.exports = {
      extend: 'apostrophe-widgets',
      label: 'Two Column Layout',
      addFields: [
        {
          name: 'special',
          label: 'Special',
          type: 'boolean'
        }
      ]
    };

widget.html

    <div class="two-column">
        <div class="column-left">
            {{ apos.area(data.widget, 'areaLeft', {
                widgets: {
                    'apostrophe-images': {},
                    'apostrophe-rich-text': {}
                }
            }) }}
        </div>
        <div class="column-right">
            {{ apos.area(data.widget, 'areaRight', {
                widgets: {
                    'apostrophe-images': {},
                    'apostrophe-rich-text': {}
                }
            }) }}
        </div>
    </div>

**Comment by boutell** [comment]
They must be in the schema, but you can set them `contextual: true` in the schema to keep them out of the modal.

**Comment by stuartromanek** [comment]
You can also configure the widget itself to be either `contextualOnly: true` (no edit UI ever) or `skipInitialModal: true` (no initial modal but edit UI still attached).

Both are good for layout widgets. Its a one or the other type option
