### ISSUE TITLE
backslashes added in assets (app.js)

### ISSUE THREAD

**Issue by israelidanny** [punkave/apostrophe#119]
When setting assets in `app.js`, there's a problem - any path I set with a subdirectory will change the slashes into back slashes `\`, and dumps them link that as an import into `master-user.css`.

That just causes them to not load. I tried different variations, and it will still make this problem.

**Comment by boutell** [comment]
Removing this as 0.5 is in maintenance mode. Reopen if a 2.0 problem is verifying.
