### ISSUE TITLE
Allowing other extensions in file upload

### ISSUE THREAD

**Issue by Danny-weebo** [punkave/apostrophe#145]
Hey, I've a snippet with a singleton files field and I wonder how can I allow to upload other extensions beside rtf pdf office txt (which is default) !?

thanks!

**Comment by benirose** [comment]
Closing this and opening #193 to track progress of adding this into apostrophe-files in the unstable branch.

**Comment by boutell** [comment]
I wrote a nice HOWTO for this that doesn't require you to restate all the
existing settings:

http://apostrophenow.org/howtos/adding-file-types-in-the-media-library.html

On Fri, Feb 20, 2015 at 5:32 PM, benirose <notifications@github.com> wrote:

> Closing this and opening #193
> <https://github.com/punkave/apostrophe/issues/193> to track progress of
> adding this into apostrophe-files in the unstable branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/145#issuecomment-75331923>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by benirose** [comment]
Thanks Tom! Your note at the bottom of the HOWTO might not be applicable any longer, and definitely isn't future proof: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

Scroll down to "Supported image formats". However, the ones we support are known to be supported in all browsers.

**Comment by boutell** [comment]
Yeah, you could tweak the language if you like to indicate it doesn't make
sense to add a format *unless* it is supported in all browsers, and leave
it at that.

On Mon, Feb 23, 2015 at 3:41 PM, benirose <notifications@github.com> wrote:

> Thanks Tom! Your note at the bottom of the HOWTO might not be applicable
> any longer, and definitely isn't future proof:
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
>
> Scroll down to "Supported image formats". However, the ones we support are
> known to be supported in all browsers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/145#issuecomment-75627187>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by benirose** [comment]
Ya that makes sense.
