### ISSUE TITLE
Gettings tags by they popularity

### ISSUE THREAD

**Issue by Danny-weebo** [punkave/apostrophe#148]
Hey! how can I sort the tags by they popularity ? 

This is an example for what I'm trying to do (notice the sizes of the fonts)
http://cdn.smugmug.com/img/help/keyword-tags/keywords-photos-website-2.gif

thanks!

**Comment by stuartromanek** [comment]
This issue seems pretty inactive and like something we're not adjusting for in the core. Closing this for now
