### ISSUE TITLE
Limiting Tags field

### ISSUE THREAD

**Issue by pixeleet** [punkave/apostrophe#157]
Hey There,

I was wondering, if there is a way to limit how many tags can be added to an item?
I've looked through the code, maybe I missed something but I found no possibility to do so.

Cheers,
David

**Comment by benirose** [comment]
Hi @pixeleet, I saw you submitted a pull request for this, but @boutell had mentioned it needing some adjustments. Did you get a chance to update it?

**Comment by pixeleet** [comment]
To my understanding it's already merged ;)
https://github.com/punkave/apostrophe/pull/159

2015-02-21 5:02 GMT+01:00 benirose <notifications@github.com>:

**Comment by benirose** [comment]
Great!
