### ISSUE TITLE
Apostrophe should give user's feedback on its saving practices

### ISSUE THREAD

**Issue by fotisp** [punkave/apostrophe#161]
When editing a rich text field, the presented toolbar should have an explicit save button which lets the user know that if their intent is to commit the changes then they should press that.

The result of pressing that button lets call it "Save" is the same a "clicking" or "double clicking" (not sure which one it is yet) outside the widgets area.

Users are getting wowed by the UI up until that point, where the question is "So how do I save this" 100% of the times without exceptions.

**Comment by benirose** [comment]
This is still a great enhancement I think A2 users would benefit from. Sadly, it's not a priority for us, however it's entirely possible that while we're [refactoring](https://groups.google.com/forum/#!topic/apostrophenow/RZoxUE6yLb4) the backend someone could knock this out. I'll move it in the backlog until we give the front end some serious attention.

**Comment by benirose** [comment]
I also renamed the issue to match the functionality we want to implement.

**Comment by boutell** [comment]
This won't be changing for 0.5 as it would be too disruptive a change given that 0.5 is in maintenance mode, but there is a parallel issue open for 2.0.
