### ISSUE TITLE
Apostrophe permissions and their extensibility

### ISSUE THREAD

**Issue by fotisp** [punkave/apostrophe#166]
I would like to ask where / how I should look at in order to really understand the permissions layer in apostrophe. Moreover I am looking to extend the User / Groups Manager in order to allow a bit more customized control of several aspects of the CMS.

For example I have a custom module with does everything as it should but I need to plug in Groups and Users permission in there. For instance, right now there are the following types of users “admin”, “editor” and “guest”, how would I go about adding an “editor” type, say “manager” who cannot do a particular action.

I have seen permissions.can(“”) , but how can I add strings to that “can” action which are customized to the current deployment. Can I do it at the module level? Or is this project wide?

Also after my hiccup with the apos[Module]Menu macro where I just needed to add the “permission” object, rather than pemission.admin, I need to understand where these checks are occurring. Because I might need to override the entire menu, and cherry peek what is available to whom.

I am comfortable enough now to hack at the right places, but I need some insight on the permission part of A2.

Best,
Fotis

**Comment by benirose** [comment]
Hi @fotisp. You might be able to find what you're looking for either in the [apostrophe-people readme](https://github.com/punkave/apostrophe-people), or by reading through the code in `apostrophe/lib/modules/permissions.js`. I'm not sure we have it well documented at the moment or if we support that. However, we are currently in the process of refactoring our auth services in the unstable branch, so we'll take that into consideration. You can read more about our refactoring on our [google group](https://groups.google.com/forum/#!topic/apostrophenow/RZoxUE6yLb4)

**Comment by fotisp** [comment]
Thanks for the update @benirose!

I will look at permissions and see what is under the hood.
