### ISSUE TITLE
Update outdated/vulnerable modules

### ISSUE THREAD

**Issue by pdehaan** [punkave/apostrophe#170]
See https://nodesecurity.io/advisories/validator_XSS_Filter_Bypass_via_Encoded_URL

You may want to update to at least **validator@2.0.0** (or newer; it looks like we're currently using [**0.4.19**](https://github.com/punkave/apostrophe/blob/a3f3bb0a0e1327c294e218d9039146d433e0ebd7/package.json#L35)).

**UPDATE:** You may also want to bump the version of **express** and **qs** and **extend** (see below).

**Comment by benirose** [comment]
I'm updating this ticket to be applicable for our 0.6 refactor, but feel free to still make a PR for the master branch (0.5) if you were able to test the results of upgrading.

**Comment by benirose** [comment]
Express was updated to 4 in the unstable branch (refactor). I'm sure we'll be addressing these as we go.

**Comment by pdehaan** [comment]
Did a quick check and everything looks good in unstable branch:

```
$ npm shrinkwrap --dev
wrote npm-shrinkwrap.json

$ nsp shrinkwrap
No vulnerable modules found

$ npm outdated --depth 0
Package        Current  Wanted  Latest  Location
connect-mongo    0.7.0   0.7.0   0.8.1  connect-mongo
glob             4.5.3   4.5.3   5.0.5  glob
mongodb         1.4.35  1.4.35  2.0.28  mongodb
```
