### ISSUE TITLE
switching place in snippet's array type 

### ISSUE THREAD

**Issue by Danny-weebo** [punkave/apostrophe#178]
Hey, by creating a snippet with an `array` field, you get in the control panel the button to "add" another value to the array, but the new item gets on top of the others "posts", how can I reverse it ? 
it would be really appreciated as its really annoying to add stuff to the array this way.

thanks!

**Comment by benirose** [comment]
@Danny-weebo: I have had this issue as well, but it really depends on the use case. You don't want to make users scroll down to the bottom of the array to edit the new thing they just added every time, but there are often cases when you want the new item to be at the end of the list.

Sadly this is not a priority for us right now. We would appreciate help with this in a Pull Request for the module it lives in (apostrophe-schemas). You'll find the code that does this on line 460 of `apostrophe-schemas\public\js\editor.js` (line 463 is the actual prepend). It would be great to have some sort of property in your schema definition determine the add order.

We do, however, have a hidden power-user feature baked in that may help with this. If you press the shift key, the arrows that let you move around the array items become double-arrows. Clicking these will send something to the top or bottom of a list, so you could add your new item to the array, fill it out, then shift+click the down arrow to send it to the bottom.

Hope this helps!

**Comment by boutell** [comment]
This was addressed in 2.0 where the array UI is dramatically nicer. It will not be changing further in 0.5 which is in maintenance mode.
