### ISSUE TITLE
Current mechanism for decorating layout with outerLayout is messy

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe#181]
We should use conditional extends if we can. This workaround for nunjucks' limitations in that area may be sufficient:

https://github.com/mozilla/nunjucks/issues/39#issuecomment-67131773

However, consider what happens on an apos-refresh and whether that still requires us to keep the regex-based mechanism around.

**Comment by benirose** [comment]
This has been addressed in the unstable branch and will be included in 0.6!
