### ISSUE TITLE
Amazon S3

### ISSUE THREAD

**Issue by blackbumer** [punkave/apostrophe#183]
Is it possible to use Amazon S3 storage for images uploads?

**Comment by boutell** [comment]
Yes. See the uploadfs module. It is configurable via the uploadfs option in
app.js.

**Comment by blackbumer** [comment]
What is about cloudinary?
I'm just trying to use apostrophe with heroku...

**Comment by boutell** [comment]
There is a new howto for this issue on apostrophenow.org. close #183
