### ISSUE TITLE
mongodb full text search and hebrew/arabic

### ISSUE THREAD

**Issue by israelidanny** [punkave/apostrophe#185]
There seems to be a really nasty behavior with the mongodb full text search and hebrew/arabic languages (unsupported by the built in analyzer/stemmer).

In the above languages, some words such as 'of'/'from'/'to' are added to the actual word. So, say - if we take the word 'reserach', to say 'to research' you would kinda glue a different word to the beginning, making it effectively look like 'toresearch'.

Now, because mongo doesn't know any of that - it sees 'research', and 'toresearch' as completely different words, and when I search for 'research' it wouldn't return 'toresearch'.. which then makes it hard to find things..

Would you have any advice on how to go about this? I think even a dumb regex search at this point would perform better than a mongodb stemmer for this. Is there any way to revert to that (I know that was the old behaviour) for a project?

**Comment by israelidanny** [comment]
In other words, is there currently a way to tell mongo "please search the old fashioned way by regex"? Or an easy way to replicate this in a module?

**Comment by boutell** [comment]
Very reasonable question. You could override apos.get and process
options.search yourself. Also I believe mongo lets you specify the stemming
language, an option we are probably not exposing yet. I don't know if it
has good Hebrew support though.

**Comment by israelidanny** [comment]
We solved it, and if anybody else needs something similar, here is a little monkey patch:
https://github.com/madebycaffeine/old-school-search

We pad the get with a method that augments the query into a regex search rather than mongo full text.

Thanks for your help Tom! :)

**Comment by boutell** [comment]
Nice! FYI I don't think your module needs to have a loader method, I think
you have it there doing nothing because you're worried something bad will
happen if you don't (:

On Wed, Jan 21, 2015 at 11:27 AM, Danny Povolotski <notifications@github.com
> wrote:

> Closed #185 <https://github.com/punkave/apostrophe/issues/185>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/185#event-222424855>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by israelidanny** [comment]
Yes! :) I'll remove it. I'm still intimidated by scary things potential to happen if a variable / method is missing in apostrophe modules :P
