### ISSUE TITLE
automatic sitemap.xml? 

### ISSUE THREAD

**Issue by israelidanny** [punkave/apostrophe#186]
we noticed that our websites that migrated to Apostrophe2 took a huge hit in SEO ranking. And one of the major downsides looks like lack of sitemap leading to a drastic drop in crawled pages.

What do you guys do right now for sitemaps?

**Comment by boutell** [comment]
We generally make a point of using semantic markup and encourage our
clients to remember the need for relevant copywriting on each page, even if
a human user would find what they wanted graphically.

We also check whether sites can be fully explored with the "lynx" command
line browser, which is much like google in what it can and can't
understand.

Also, this tool I built is useful to check navigability (I apologize for
any i18n bugs): http://searchvision.boutell.com/

These Google Sitemaps are usually out of date, and when they are out of
date they are worse for your SEO than no sitemap at all. Of course it's
possible to write an apostrophe module that generates an up-to-date one,
but I'm not convinced this is the best way to improve your SEO. Only
empirical testing would show for certain.

The apostrophe-site-map module exists. It is currently only intended as a
tool for content strategists, not as a google sitemap generator, but it's
obviously a step in that direction, and we'd accept pull requests to make
it a full sitemap generator for those who want one.


On Wed, Jan 21, 2015 at 11:24 AM, Danny Povolotski <notifications@github.com
> wrote:

> we noticed that our websites that migrated to Apostrophe2 took a huge hit
> in SEO ranking. And one of the major downsides looks like lack of sitemap
> leading to a drastic drop in crawled pages.
>
> What do you guys do right now for sitemaps?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/186>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by israelidanny** [comment]
Actually, from my experience a correct sitemap mechanism is quite an SEO advantage. 

Google gives you an API to send a crawl request based on a sitemap, and from what I've seen it makes a huge difference. Especially in sites with time sensitive content and lots of pages (news/content-driven sites/blogs with competition e.t.c). We've noticed that if we published information before our competitors, and made sure our sitemap gets generated, pinged to google instantly, it makes a huge, huge difference.

The trick is to either have a frequently re-cached sitemap generator, or something like that - to never create an "expired sitemap" situation.

That's why I was asking if you have any automatic solution.

I'll see if we end up developing a module, and publish it here in this issue thread.

**Comment by boutell** [comment]
Thanks for sharing your experience with this issue.

I suggest looking at the apostrophe-site-map module I mentioned earlier,
since it is a long step down the road to being what you want.

On Wed, Jan 21, 2015 at 11:50 AM, Danny Povolotski <notifications@github.com
> wrote:

> Actually, from my experience a correct sitemap mechanism is quite an SEO
> advantage.
>
> Google gives you an API to send a crawl request based on a sitemap, and
> from what I've seen it makes a huge difference. Especially in sites with
> time sensitive content and lots of pages (news/content-driven sites/blogs
> with competition e.t.c). We've noticed that if we published information
> before our competitors, and made sure our sitemap gets generated, pinged to
> google instantly, it makes a huge, huge difference.
>
> The trick is to either have a frequently re-cached sitemap generator, or
> something like that - to never create an "expired sitemap" situation.
>
> That's why I was asking if you have any automatic solution.
>
> I'll see if we end up developing a module, and publish it here in this
> issue thread.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/186#issuecomment-70873741>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by benirose** [comment]
Looks like we can close this out, feel free to add the module here if you publish it.

**Comment by boutell** [comment]
Re opening because this is on radar for our clients lately too. It is likely we will build our own XML sitemap generator soon if no one else adapts the informational sitemap generator. One issue is that it must address all published snippets with a published index page, not just regular pages. There must also be provision to generate custom links. An incomplete sitemap is worse than none.

**Comment by benirose** [comment]
Always a man of his word, Tom has built said module: https://github.com/punkave/apostrophe-site-map.

This can now be closed with joyful resolution!
