### ISSUE TITLE
Cross-domain includes can't include naturally from their own folders

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe#188]
If my nunjucks template includes a file from apostrophe-donate as "donate:formWrapper.html", and that file attempts to include "form.html", it cannot find a "form.html" that lives in the donate module.

This is a rather deep bug between nunjucks and our nunjucksLoader.js, which has no way of communicating a list of paths to future include calls from the resulting source code. It's going to keep on using the same loader.

Or maybe it's not that deep at all and I just need to call the other loader and return the source it generates.

**Comment by benirose** [comment]
This has been addressed in the unstable branch (0.6), any reason to fix this in 0.5?

**Comment by boutell** [comment]
I think we can live with it in 0.5. Thanks for digging through these Ben!
