### ISSUE TITLE
Apostrophe admin styles are highly coupled with apostrophe-sandbox

### ISSUE THREAD

**Issue by lojack** [punkave/apostrophe#189]
This is somewhat related to #101

As it stands the only way to start a new apostrophe website is to clone apostrophe-sandbox, remove everything you don't want, and override the things you do want with your own styles. This leads to a lot of duplicated CSS rules, and a lot of unused CSS rules. Additionally, if Apostrophe ever introduces changes that require changes to the admin CSS, this means I need to manually update the CSS in every single project separately. This isn't very DRY. 

I think it would make sense to do what's suggested in #101 and have all the apostrophe CSS rules globally scoped as well as pull all the styles involved in the admin side of things into this project, and inject the admin stylesheets into the aposStylesheets() tag.

**Comment by benirose** [comment]
Thanks for the suggestion. We've actually been working on a boiler plate and a CLI, but haven't gotten to spend the time we want on it (and even less time documenting their use).

You can check them out and help move them along:
https://github.com/punkave/apostrophe-boilerplate
https://github.com/punkave/apostrophe-cli

The CLI is a globally installed NPM module that pulls in the boiler plate to create new projects. It also allows you to run any apostrophe commands you would normally run with `node app apostrophe:COMMAND`.

Hope this is helpful in the mean time, but we are definitely also interested in cleaning up our CSS. Feel free to submit pull requests with changes to the sandbox if you have time to contribute.

**Comment by benirose** [comment]
For the time being, we are in the process of making some big steps towards refactoring our back end code, and likely won't get towards front-end enhancements for some time. I'm going to put this ticket in our backlog for now and we will revisit it when we are focusing on refactoring our front-end code.

**Comment by boutell** [comment]
This was addressed for 2.0. It will not be changing in 0.5 for stability reasons.
