### ISSUE TITLE
Find LESS middleware that supports 2.2

### ISSUE THREAD

**Issue by benirose** [punkave/apostrophe#192]
Our current LESS middleware only supports 1.7. In our Unstable branch, we have already converted the minify code to use 2.2. We will want to either find, fork, or create our own middleware that supports 2.2 as well.

**Comment by kylestetz** [comment]
Breaking news: [less-middleware now supports the latest and greatest](https://github.com/emberfeather/less.js-middleware/commit/80156f85127fbbf38de5013a959d8ea141aef54e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R12).

**Comment by boutell** [comment]
That was easy!

On Fri, Feb 27, 2015 at 8:41 AM, Kyle Stetz <notifications@github.com>
wrote:

> Breaking news: less-middleware now supports the latest and greatest
> <https://github.com/emberfeather/less.js-middleware/commit/80156f85127fbbf38de5013a959d8ea141aef54e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R12>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/192#issuecomment-76395618>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by benirose** [comment]
Sometimes you just gotta stir the pot!
