### ISSUE TITLE
Allow easy apppending of file upload types in app.js

### ISSUE THREAD

**Issue by benirose** [punkave/apostrophe#193]
Per #145:

"We should provide a neat and tidy option for it, and for adding new files to an existing group without restating everything"

**Comment by boutell** [comment]
This already exists in the 0.6 refactor. See the fileGroups option in apostrophe-files/index.js

**Comment by boutell** [comment]
Reopening because currently you can't just add to / manipulate the existing list, you have to start from scratch.

**Comment by benirose** [comment]
Yeah, I think this is more about having easily appended file types from app.js.

**Comment by boutell** [comment]
Right... what we have in 0.6 already makes it easy to override the file
types from app.js, but it is not yet easy to append.

On Tue, Apr 28, 2015 at 11:33 AM, benirose <notifications@github.com> wrote:

> Yeah, I think this is more about having easily appended file types from
> app.js.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/193#issuecomment-97106853>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by benirose** [comment]
Correct, I'll change the name of this issue to reflect that, and remove it from the milestone, since that's really more a nice to have than something we should hinge 0.6's completeness on.

**Comment by benirose** [comment]
Whoops, this wasn't even the 0.6 version of the ticket. Putting this one in the backlog.

**Comment by boutell** [comment]
This was addressed for 2.0. It will not be changing in 0.5 which is in maintenance mode.
