### ISSUE TITLE
Improved error detection when no database exists

### ISSUE THREAD

**Issue by mkopinsky** [punkave/apostrophe#194]
If you launch an apostrophe site without doing an `apostrophe:reset`, when you try hit a page it errors as follows:

```
:: 2015-02-23T12:04:38-0500: template error at /
Current user: none
[Error: template not found: APP_PATH/views/pages/notfound.html]
```

This error isn't wrong per se, because there legitimately is a 404 (there is no page with the slug '/') and I indeed don't have a notfound.html page, but this is kinda missing the point - the entire database is missing.

It would be nice if Apostrophe, when starting up, did certain sanity checks like "Is there a `pages` collection?" and if not, warns in the server logs.

**Comment by benirose** [comment]
This is a good enhancement is is definitely going to be part of 0.6 (currently the `unstable` branch). We'll see if it's something we want to spend time adding into 0.5 as well.

**Comment by boutell** [comment]
For 2.x we made the call to spin up everything via parked pages, i.e. there is no bootstrap task. So we won't be calling it an error to have no database, although we could print a helpful clue if adding a parked page that wasn't there before.
