### ISSUE TITLE
new warning in node 0.13

### ISSUE THREAD

**Issue by simlevesque** [punkave/apostrophe#195]
Hi, I started to use the latest node and I get the following warning : 

`.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.`

just a heads up ! it's not a problem.

**Comment by kylestetz** [comment]
Thanks @simlevesque, we'll check this out. Let us know if you encounter any other warnings related to 0.13.

**Comment by boutell** [comment]
@simlevesque, any chance you can post a more complete stack trace? Curious
if it's something we're doing, or something one of our dependencies is
doing.


On Fri, Feb 27, 2015 at 8:35 AM, Kyle Stetz <notifications@github.com>
wrote:

> Thanks @simlevesque <https://github.com/simlevesque>, we'll check this
> out. Let us know if you encounter any other warnings related to 0.13.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/195#issuecomment-76394861>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by simlevesque** [comment]
I can't post a larger stack, it's all I have. But I also use the js version
of BSON instead of the C++ version so it might be this.

2015-02-27 8:47 GMT-05:00 Tom Boutell <notifications@github.com>:

> @simlevesque, any chance you can post a more complete stack trace? Curious
> if it's something we're doing, or something one of our dependencies is
> doing.
>
>
> On Fri, Feb 27, 2015 at 8:35 AM, Kyle Stetz <notifications@github.com>
> wrote:
>
> > Thanks @simlevesque <https://github.com/simlevesque>, we'll check this
> > out. Let us know if you encounter any other warnings related to 0.13.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/punkave/apostrophe/issues/195#issuecomment-76394861
> >.
> >
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330 | punkave.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/195#issuecomment-76396376>.
>



-- 

Simon Lévesque | Développeur Web
http://amkroma.com/
simlevesque@amkroma.com | 1.514.209.1690

**Comment by boutell** [comment]
0.5 is standardized on node 0.10.x, this shouldn't be an issue with 2.0.0.
