### ISSUE TITLE
Discussion: support for multiple slideshow templates, switching between widget types in general

### ISSUE THREAD

**Issue by kylestetz** [punkave/apostrophe#197]
#### Slideshow are frustrating.

Relying on one `slideshow.html` file to be used across an entire site has been problematic. I am proposing a new pattern based on our experience with [apostrophe-schema-widgets](https://github.com/punkave/apostrophe-schema-widgets) that would allow developers the ability to write multiple slideshows to be used in different situations.
#### We should treat them like we treat schema widgets.

If `apostrophe-slideshow` became a module in 0.6, it could be configured to have multiple types, each with their own schema:

``` javascript
// app.js
...
'apostrophe-slideshow': {
  types: [
    {
      // template will output an element with a background-image applied to it.
      // the schema allows simple control over the background-position.
      name: 'cover',
      schema: [
        {
          name: 'backgroundPosition',
          type: 'select',
          choices: [
            { label: 'top',    value: 'top'    },
            { label: 'right',  value: 'right'  },
            { label: 'bottom', value: 'bottom' },
            { label: 'left',   value: 'left'   }
          ]
        }
      ]
    },
    {
      // template will simply output an <img> tag
      name: 'img'
    }
  ]
}
...
```

...and then the `lib/modules` directory would contain corresponding files:

```
lib
└ modules
  └ apostrophe-slideshow
    └ views
      ├ cover.html
      └ img.html
```

...and when defining an `apos.area` you would specify the available slideshow types in a `slideshow` configuration:

``` twig
{{
  apos.area(page, 'myArea', {
    controls: ['slideshow'],
    slideshow: ['cover', 'img']
  })
}}

or alternatively

{{
  apos.area(page, 'myArea', {
    controls: ['cover', 'img']
  })
}}
```

...and this would all result in a slideshow modal containing a dropdown to select the type of slideshow to use. The schema could be presented below the image selection area as part of the modal.
#### We could build macros to support the creation of custom slideshows.

Our slideshow currently does a lot of cool magic... It applies the `projector` jquery plugin automatically, it adds metadata if it exists (and the user asks for it), etc. etc. We could easily build some macros (akin to the stuff in `formMacros.html`) that allow us to drop in support for this kind of stuff. Modularizing our slideshow tools will allow us to scale back the functionality as well as we currently scale it up.

Thoughts?

**Comment by boutell** [comment]
All widgets will be modules in 0.6. There will be an apostrophe-widget module that all other widgets (can conveniently) extend, and an apostrophe-slideshow module that extends that and is easily extended in turn.

So, the bit here that isn't going to come for free in 0.6 is the bit where the type of a slideshow is mutable... the user can change their mind and make a slideshow of type X into a slideshow of type Y without starting over.

That is an issue I'd love to see addressed more globally: it should be possible to express which widget types are intraconvertible, and we should work out the right UI for changing a widget from one type to another.

So here's what your example looks like reformatted into the A2 0.6 idiom, extending types the [moog](https://github.com/punkave/moog) way:

```javascript
// app.js, or in modules
...
'slideshow-cover': {
 extend: 'apostrophe-slideshow',
 label: 'Slideshow (Cover)',
 controlName: 'cover',
 compatible: [ 'slideshow-img' ]
 addFields: [
   {
     name: 'backgroundPosition',
     type: 'select',
     choices: [
       { label: 'top',    value: 'top'    },
       { label: 'right',  value: 'right'  },
       { label: 'bottom', value: 'bottom' },
       { label: 'left',   value: 'left'   }
     ]
   }
 ]
},
'slideshow-img': {
 extend: 'apostrophe-slideshow',
 controlName: 'img',
 compatible: [ 'slideshow-cover' ]
 label: 'Slideshow (Image)'
}

// Folder structure
```

```
lib/modules/slideshow-cover
 views
   slideshow.html

lib/modules/slideshow-img
 views
   slideshow.html
```

```jinja
// nunjucks template

{{
 aposArea(page, 'myArea', {
   controls: [ 'cover', 'img' ]
 })
}}
```

If a widget has a "compatible" property then it gets a "switch to" dropdown or something. We can think about whether this is ever automatic, or something that's left to frontend developers to decide when configuring their sites, on the understanding that it only works if the types are indeed coded to be compatible.

It's up to the programmer to make sure their code does not assume any "required" properties are present and has a sane fallback behavior when someone switches from a type with a less detailed schema.

I'm excited about this.

**Comment by stuartromanek** [comment]
In 0.5 this could always have been hacked in by passing extra configuration to the slideshow widget and deciding what to do in the template.

In 0.6, obviously, this rules. Closing.

**Comment by boutell** [comment]
There was some discussion of making it possible to switch the type of an existing widget to a "compatible" type here, but I agree this can be closed. That idea will come back if it was a winner. I think it's more likely we'll use a "subtype" field in the widget editor itself to avoid ballooning the number of items in the "add content" menu.
