### ISSUE TITLE
Decide if JS and CSS for schemas should be in the "always" scene

### ISSUE THREAD

**Issue by benirose** [punkave/apostrophe#219]

**Comment by benirose** [comment]
We had talked about the front end code for schemas being broken out from the user scene so that you could use schemas without having to change scenes. Is still this something we want to do, or was that solved by implementing the req.scenes code?

If we do, should we also include modals for all people? If that's the case, is anything still in user?

**Comment by boutell** [comment]
Snippet admin would be a fine thing to leave in user, even if we decide
modals and schemas are "always on."

On Fri, Mar 20, 2015 at 4:58 PM, benirose <notifications@github.com> wrote:

> We had talked about the front end code for schemas being broken out from
> the user scene so that you could use schemas without having to change
> scenes. Is still this something we want to do, or was that solved by
> implementing the req.scenes code?
>
> If we do, should we also include modals for all people? If that's the
> case, is anything still in user?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/219#issuecomment-84143284>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by benirose** [comment]
True. Not sure this is even a decision we need to make right now, but I wanted to document it. Now that it's much easier to change scenes before page load, the case for it is much weaker.

**Comment by boutell** [comment]
Going to keep this as a "user" thing, and leverage the ability to change scenes before page load.
