### ISSUE TITLE
"Page versions" menu only works properly once unless you refresh page

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe#220]
On page versions, if the page versions is opened, closed and opened again it doesn’t display the page versions anymore until the page is refreshed. Looks like a bug recreating the apos-modal-tabs. Is this an apostrophe bug or a site conflict? Easy enough to work around by refreshing or going back to live then back to edit.

**Comment by stuartromanek** [comment]
This seems to work fine, closing

![img](http://g.recordit.co/KoaEu98JCE.gif)
