### ISSUE TITLE
Refactor templates.addToApos as templates.addHelpers

### ISSUE THREAD

**Issue by benirose** [punkave/apostrophe#226]
When we want to add functions to the apos object for use in nunjucks templates, we currently have written a function called `addToApos`. We realized that these are helper functions, as defined by multiple MVC libraries. This is a good name, and we should use it too.

One thing to consider, is that it doesn't translate as well if you're trying to add an object/property to the apos object. Perhaps leave both of them available?

**Comment by jth-** [comment]
Done.
