### ISSUE TITLE
Media Library: File upload doesn't give feedback when uploading invalid file type

### ISSUE THREAD

**Issue by jth-** [punkave/apostrophe#231]
When a user tries to upload an unsupported filetype, they should receive an error message showing that. Currently the message is only visible in the server logs.

**Comment by benirose** [comment]
Created #237 to track this change in 0.6 refactoring.

**Comment by stuartromanek** [comment]
We now error on the front end but its just 'err', should also be more descriptive in 0.6

**Comment by stuartromanek** [comment]
actually 0.6 does give a good description of the error. This doesn't feel like a critical thing to fix in 0.5, closing.
