### ISSUE TITLE
Impossible to display page menu

### ISSUE THREAD

**Issue by hikkyu** [punkave/apostrophe#232]
Hello!

I can't see the page menu with the admin account or another create with people extension.
The only things I have is a 404.

Same problem with the sandbox

Did i missed something?

Thank's

**Comment by kylestetz** [comment]
Did you run `node app apostrophe:reset` in the command line first? It sounds like you might not have a database set up yet for either of your sites.

**Comment by hikkyu** [comment]
RTFM :-)
Sorry about this issue ^^ 
Everything is right now

**Comment by kylestetz** [comment]
No worries, glad you got it sorted out!
