### ISSUE TITLE
Apostrophe should give user's feedback on its saving practices (0.6)

### ISSUE THREAD

**Issue by benirose** [punkave/apostrophe#244]
Let's see if we can work in #161 while refactoring editable areas.

**Comment by boutell** [comment]
This got a lot easier to arrange recently due to the addition of certain events, and I believe there are designs for it, right @stuartromanek?

**Comment by stuartromanek** [comment]
There are designs for a page save interaction that I think @bobclewell was implementing, is that right?

We might also think about implementing a few confirmation notifications when editing pieces in a modal

**Comment by boutell** [comment]
What ticket is all that in? Is this one a dupe now?

**Comment by stuartromanek** [comment]
page saving is specifically here https://github.com/punkave/apostrophe/issues/979

**Comment by boutell** [comment]
Thanks Stuart. I think that ticket is quite sufficient — the only other case of note is pieces, and they follow normal, boring "click save to save" semantics. I'm going to close this one as a dupe.
