### ISSUE TITLE
i18n page url

### ISSUE THREAD

**Issue by hikkyu** [punkave/apostrophe#246]
Hello!

I need to show two product list with language context. I imagine something like that:
- //mysite.com/fr/lessons
- //mysite.com/en/lessons

I think i18n content is not implemented yet, so I guess I can filter by tag for the language and I dont care about to make two entry for the same lesson at this time.

Product page is the same custom module, I got this part. How can i do that? is it possible ?

Actually I tried to create a page fr and a subpage product but I got a server error.

    Cannot read property 'page' of undefined

There is my lesson module index
```twig
{% extends "layout.html" %}
{% include "lessonsMacros.html" %}

{% block bodyClass %}{{ super() }} lessons{% endblock %}

{# Output the current content of the page, with buttons to edit it #}

{% block main %}
  <h1>{{ __('All lessons') }}</h1>
  {{ aposArea() }}
  {{ renderLessonsPreviews(items, page.url) }}
{% endblock %}
```

There is my lessonMacro
```twig
{# Preview lesson used in list page #}
{% macro renderLessonsPreviews(items, pageUrl) %}
  {% if items %}
    <div itemscope itemtype="http://schema.org/Product">
      {% for item in items %}
        {{ renderLessonPreview(item, pageUrl) }}
      {% endfor %}
    </div>
  {% else %}
    <h4>{{ __('There are no lessons yet.') }}</h4>
  {% endif %}
{% endmacro %}

{% macro renderLessonPreview(item, pageUrl) %}
  <h4 itemprop="name">{{ item.title }}</h4>
{% endmacro %}

{# Full lesson used in detail page #}
{% macro renderLesson(item, pageUrl) %}
  <h4 itemprop="name">{{ item.title }}</h4>

  <p>AVIS {{ item.rating }}</p>
{% endmacro %}

{# Home push #}
{% macro renderLessonsPushes(items, pageUrl) %}
  {% if items %}
    <div itemscope itemtype="http://schema.org/Product">
      {% for item in items %}
        {{ renderLessonPreview(item, pageUrl) }}
      {% endfor %}
    </div>
  {% else %}
    <h4>{{ __('There are no lesson yet.') }}</h4>
  {% endif %}
{% endmacro %}
```

This module works well on a root page

Thank's

**Comment by boutell** [comment]
If you think this is a bug in Apostrophe, please provide a specific test
case with sample code that reproduces the problem. If it is a general
question about workarounds for i18n, I suggest you take it to the
apostrophenow google group.

On Tue, Apr 28, 2015 at 10:01 AM, Damien Berseron <notifications@github.com>
wrote:

> Hello!
>
> I need to show two product list with language context. I imagine something
> like that:
>
>    - //mysite.com/fr/lessons
>    - //mysite.com/en/lessons
>
> I think i18n content is not implemented yet, so I guess I can filter by
> tag for the language and I dont care about to make two entry for the same
> lesson at this time.
>
> Product page is the same custom module, I got this part. How can i do
> that? is it possible ?
>
> Actually I tried to create a page fr and a subpage product but I got a
> server error.
>
> Cannot read property 'page' of undefined
>
> There is my lesson module index
>
> {% extends "layout.html" %}
> {% include "lessonsMacros.html" %}
>
> {% block bodyClass %}{{ super() }} lessons{% endblock %}
> {# Output the current content of the page, with buttons to edit it #}
>
> {% block main %}
>   <h1>{{ __('All lessons') }}</h1>
>   {{ aposArea() }}
>   {{ renderLessonsPreviews(items, page.url) }}
> {% endblock %}
>
> There is my lessonMacro
>
> {# Preview lesson used in list page #}
> {% macro renderLessonsPreviews(items, pageUrl) %}
>   {% if items %}
>     <div itemscope itemtype="http://schema.org/Product">
>       {% for item in items %}
>         {{ renderLessonPreview(item, pageUrl) }}
>       {% endfor %}
>     </div>
>   {% else %}
>     <h4>{{ __('There are no lessons yet.') }}</h4>
>   {% endif %}
> {% endmacro %}
>
> {% macro renderLessonPreview(item, pageUrl) %}
>   <h4 itemprop="name">{{ item.title }}</h4>
> {% endmacro %}
> {# Full lesson used in detail page #}
> {% macro renderLesson(item, pageUrl) %}
>   <h4 itemprop="name">{{ item.title }}</h4>
>
>   <p>AVIS {{ item.rating }}</p>
> {% endmacro %}
> {# Home push #}
> {% macro renderLessonsPushes(items, pageUrl) %}
>   {% if items %}
>     <div itemscope itemtype="http://schema.org/Product">
>       {% for item in items %}
>         {{ renderLessonPreview(item, pageUrl) }}
>       {% endfor %}
>     </div>
>   {% else %}
>     <h4>{{ __('There are no lesson yet.') }}</h4>
>   {% endif %}
> {% endmacro %}
>
> This module works well on a root page
>
> Thank's
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/246>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by hikkyu** [comment]
Ok thank's
