### ISSUE TITLE
Make aposAreaImage/apos.files.findImage() smarter 

### ISSUE THREAD

**Issue by jsumnersmith** [punkave/apostrophe#247]
Tom and I chatted about making this nunjucks helper smarter in that it could search at a depth for you. The use case is a schema widget with a slideshow buried in it. I want that slideshow's first image, but now I have to use crusty old dot syntax to get at it. I should be able to pass the schema widget in as my  `area` and then have apostrophe return the first image it can find.

**Comment by boutell** [comment]
To  be a little more precise, you would be able to pass your area in, and if the first image happened to be buried in some sub-area in a schema widget inside that area, it would still work.

It could also be made to work with page objects but that's not really the use case at hand and it could turn out badly - an obsolete area no longer used in templates could be the source of the images. So we should stick to finding things in areas, but get smarter at finding things in sub-areas.

**Comment by boutell** [comment]
(In truth, you could still have this problem of old images coming up with schema widgets, if you change their schemas. But probably not very often.)
