### ISSUE TITLE
Manage View for Blog Posts (Blog-2)

### ISSUE THREAD

**Issue by jsumnersmith** [punkave/apostrophe#250]
When attempting to batch edit (i.e. delete) many blog posts (or subclasses of blog posts), there's no easy way to really get rid of them quickly. They're hidden in the reorganize interface, and therefore you have navigate to each page and delete it there.

**Comment by boutell** [comment]
Yes, we need that manage view

On Wed, May 13, 2015 at 3:08 PM, Joel Smith <notifications@github.com>
wrote:

> When attempting to batch edit (i.e. delete) many blog posts (or subclasses
> of blog posts), there's no easy way to really get rid of them quickly.
> They're hidden in the reorganize interface, and therefore you have navigate
> to each page and delete it there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/250>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
It is done, thanks to @benirose
