### ISSUE TITLE
Rich Text: CKEditor should default to the first 'style' when an Area is created

### ISSUE THREAD

**Issue by stuartromanek** [punkave/apostrophe#251]
Right now CKEditor starts you off with an unclassed `<div>` tag (or a forced `<p>` tag in the case of `InitialContent`). The editor should default to markup from the `style` array passed into it. Perhaps the first item (Usually Normal Text, a `<p>` tag)

CKEditor has an API for setting this explicitly 
http://docs.cksource.com/ckeditor_api/symbols/CKEDITOR.config.html#.font_style

`InitialContent` should probably also take this into account?

The win here being that if you have an Area / Text Singleton that can only be a single style (a heading, for example):
1. You don't have to write unsemantic CSS that forces an element to be something it's not
```css
.something-special .apos-area div {
font-size: 3em; /** something very headline'y **/
}
```
And 2. The correct markup and style is applied upon rendering so the user doesn't have to select it from the style dropdown (also potentially confusing because you're switching from an element that you can't switch back)

**Comment by jth-** [comment]
Closed by #548
