### ISSUE TITLE
Complete Second Chance Login refactor

### ISSUE THREAD

**Issue by jsumnersmith** [punkave/apostrophe#254]
Let's not forget to implement the secondChanceLogin method in pages/index.js.

**Comment by boutell** [comment]
I'd like this to wind up in a separate module hopefully (still in the core
npm module)

On Thu, May 21, 2015 at 10:10 AM, Joel Smith <notifications@github.com>
wrote:

> Let's not forget to implement the secondChanceLogin method in
> pages/index.js.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/254>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
Similar to #371, but second chance login means if you reach a page that you don't have permissions to access and you aren't logged in, you get redirected to `/login`

**Comment by boutell** [comment]
This was released for 2.x.
