### ISSUE TITLE
Should we create an Apostrophe CMS organization?

### ISSUE THREAD

**Issue by jsumnersmith** [punkave/apostrophe#257]
Hey crew!

It's been an idea for a while, but we're wondering if we should release Apostrophe and it's ecosystem into an Apostrophe organization on Github.

About a year ago, I reached out to Github about getting the 'Apostorphe' organization, but it's taken as a username and the user never responded about giving it up to us. As an alternative, we could do `apostrophecms` like our twitter handle. 

Some of the advantages of having an organization are that we can create some project-management oriented repos as a part of the organization. This came up today as part of a conversation about improving the UI of Apostrophe. There's also uses for pushing the documentation forward, etc. 

I think it'd be an important part of making Apostrophe _more_ open-source, i.e. that it isn't P'unk Ave's Apostrophe, even though we are the corporate stewards. 

What do you all think?

**Comment by geoffdimasi** [comment]
Sounds like an interesting idea. All except for the idea that we are corporate.

**Comment by jsumnersmith** [comment]
For sure, @geoffdimasi. Never meant to indict P'unk Ave as corporate...

**Comment by kylestetz** [comment]
:+1: for it. I think `apostrophecms` is a fine organization name.

**Comment by kylestetz** [comment]
[It is done.](https://github.com/apostrophecms)

**Comment by boutell** [comment]
A+.


On Thu, May 28, 2015 at 3:35 PM, Kyle Stetz <notifications@github.com>
wrote:

> It is done. <https://github.com/apostrophecms>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/257#issuecomment-106574752>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jsumnersmith** [comment]
I'm re-opening this, because we ultimately decided to not move in that direction for the time being. we have secured `github.com/apostrophecms`, but we're not making the transition at this time.
