### ISSUE TITLE
Ideas for JS and LESS style guides?

### ISSUE THREAD

**Issue by jsumnersmith** [punkave/apostrophe#261]
Hey All,

We're moving towards creating a better, more well-organized frontend for Apostrophe. Before we stand on the precipice, I wonder if want to take the time to create and adopt JS and LESS style guides to help us and future contributors to Apostrophe. Here's an example of what I mean:

https://github.com/rwaldron/idiomatic.js

Has anyone run into any other guides that would be worth looking at?

**Comment by kylestetz** [comment]
I've always admired airbnb's [ES5 styleguide](https://github.com/airbnb/javascript/tree/master/es5). Very similar.

**Comment by jsumnersmith** [comment]
I also found Github's styleguide for their frontend styling. It's a bit more than we might need, but here it is http://primercss.io/
