### ISSUE TITLE
The manage view of pieces should be sortable and schema driven.

### ISSUE THREAD

**Issue by jsumnersmith** [punkave/apostrophe#273]
It should be easy to add new fields to the manage view of a given piece. This likely means that we need to add this as a configurable option in schemas.

Also, any field that appears in a manage view should have a click event on the title that sorts the pieces accordingly.

**Comment by stuartromanek** [comment]
![bert-bravo](https://cloud.githubusercontent.com/assets/1889830/8015801/d06e273a-0ba9-11e5-8734-85954a01df59.gif)

**Comment by boutell** [comment]
Boom
