### ISSUE TITLE
how find blog by tags on onepage.

### ISSUE THREAD

**Issue by noobthinker** [punkave/apostrophe#275]
example:
            blog path:/cms-demo/cityA
            blog left menu: foodA,foodB,foodC...etc.
            tags:food
   other blog
             blog path:/cms-demo/cityB
             blog left menu: foodX,foodY,foodZ...etc.  
             tags:food
how i find the cityA's blog by tag:food? by other tag like cityA or cityB ?

**Comment by boutell** [comment]
I'm not quite sure what you're asking to do. Are you trying to fetch blog posts with a particular tag?

**Comment by boutell** [comment]
Closing this for lack of input, but feel free to take it to the apostrophenow google group for wider discussion with more specifics:

https://groups.google.com/forum/#!forum/apostrophenow
