### ISSUE TITLE
What is the current state of translating content?

### ISSUE THREAD

**Issue by nilssolanki** [punkave/apostrophe#276]
Dear Apostrophe Team

I have been searching for a bit and only found an issue from 2013 which includes a pull request to translate templates (https://github.com/punkave/apostrophe/issues/69).

Is there currently a good way to translate the page content in apostrophe?

**Comment by boutell** [comment]
We're pursuing this in a project of our own right now, so in a few weeks
we'll have an answer that works, at least for some cases.

On Tue, Jun 30, 2015 at 4:14 AM, nilssolanki <notifications@github.com>
wrote:

> Dear Apostrophe Team
>
> I have been searching for a bit and only found an issue from 2013 which
> includes a pull request to translate templates (#69
> <https://github.com/punkave/apostrophe/issues/69>).
>
> Is there currently a good way to translate the page content in apostrophe?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/276>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
The apostrophe-localization module goes a long way in answering this issue, and opening new issues there is the best course if you have further questions.
