### ISSUE TITLE
Alias conflicts

### ISSUE THREAD

**Issue by jth-** [punkave/apostrophe#294]
If you extend a class that has an alias but the subclass something different, the subclass inherits the superclass's alias and conflicts by default.

i.e.

If `project-users` extends `apostrophe-users`, but `apostrophe-users` is aliased to `users`, `project-users` will have the alias `users` as well and cause an error on Apostrophe startup. To make this work right now, you have to override the alias in `project-users`. 

Would proper subclass behavior be to blow away aliases of superclasses?

**Comment by boutell** [comment]
That would be a nice change for sure.

**Comment by boutell** [comment]
The correct fix is to report conflicts at startup as a warning. Automatically blowing aliases away would be a bc break in projects that work today because they don't actually touch the aliases.

**Comment by boutell** [comment]
... And we already have that, as a hard error, so this is as good as it can get. Closing.
