### ISSUE TITLE
Fix bug that is scrolling all the way to the top when a user cancels a modal

### ISSUE THREAD

**Issue by alohaas** [punkave/apostrophe#297]
Using the native confirm dialog causes the page to scroll to the top each time and we want the page to remain where the user was interacting with the modal when they close it by canceling.

Can we design our own apostrophe-dialog module?

**Comment by kylestetz** [comment]
We talked about the possibility of saving half-baked forms into localStorage, which might remove the need for the warning altogether. Some other interface might need to be designed for that feature to work— maybe a "Recover unfinished work" sort of link at the top of the form.

Thoughts?

**Comment by boutell** [comment]
0.6 has the ability to serialize a form that isn't passing all validators
yet, which could be helpful in implementing the local storage trick,
someday.

But, there will always be some need to confirm stuff we can't make "no big
deal" to undo.

So we ought to implement a confirm modal that we're happy about.

We would need to get used to invoking it asynchronously — the built in
confirm is a very special snowflake in its ability to make the whole
browser wait — but we wouldn't have to blow up the paradigm.

It should be a proper subclass of apostrophe-modal IMHO.


On Fri, Jul 17, 2015 at 3:19 PM, Kyle Stetz <notifications@github.com>
wrote:

> We talked about the possibility of saving half-baked forms into
> localStorage, which might remove the need for the warning altogether. Some
> other interface might need to be designed for that feature to work— maybe a
> "Recover unfinished work" sort of link at the top of the form.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/297#issuecomment-122380658>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by alohaas** [comment]
I would love to not have a dialog box.
I'm not sure if there would be a need for saving progress on a widget editor. 
How complex have our widget editors become? 
I could see a saving progress on pieces, but that's what unpublished is for, no?

Maybe widget-based 'history' tab for undoing to previous versions of the widget...

**Comment by kylestetz** [comment]
Why don't we make a point to incorporate this in our upcoming design/ux conversations... Seems like something that requires some ideation!

**Comment by alohaas** [comment]
Yes please

**Comment by boutell** [comment]
Not confirming at all is of course an option for something like a widget editor, however we have had people sob when they lost a lot of work editing a schema widget for instance.

**Comment by boutell** [comment]
(The confirmation prompts were added relatively recently in response to specific client feedback.)

**Comment by boutell** [comment]
Update: confirm() is not causing the scrolling (see sample code below for a demonstration that this doesn't happen when launching confirm from a link at the bottom of a tall page).

The scrolling is probably caused by the mechanism that's supposed to bring you back to where you were before the modal opened, which is perhaps not working properly. 

I am changing the title of this issue to reflect that confirm() is not the cause. But feel free to open a ticket about confirm() just being gross and tacky and worth replacing.

```javascript
<html>
<head>
</head>
<body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script type="text/javascript">
		var i;
		for (i = 0; (i < 1000); i++) {
			var $p = $('<p></p>');
			$p.text(i + 1);
			$('body').append($p);
		}
		$('body').append('<a href="#" data-confirm>Confirm!</a>');
		var $confirm = $('[data-confirm]');
		$confirm.on('click', function() {
			if (confirm('Do you mean it?')) {
				alert('Okay.');
			} else {
				alert('I knew you would wimp out.');
			}
			return false;
		});
	</script>
</body>
</html>
```

**Comment by boutell** [comment]
(Most of the discussion on this thread is a long way from the original issue, but it sounds like it'll find a home in the upcoming design sprint.)

**Comment by boutell** [comment]
This bug is fixed. A "return false" was missing, so it followed the href (#) which takes you to top of page.
