### ISSUE TITLE
Add unique _id to every widget

### ISSUE THREAD

**Issue by suhmantha1** [punkave/apostrophe#316]
For versions, we want to be able to tell what specifically has been moved and edited

**Comment by jth-** [comment]
@boutell you have a commit from almost a year ago here that references this issue, any thoughts on whether this is still a thing?

**Comment by boutell** [comment]
This is done, widgets have unique IDs. They are not cryptographically awesome unique IDs, but they are just used to distinguish widgets within a single page, so I'm good with that.
