### ISSUE TITLE
Attachments: Files widget uses h1 tag in title

### ISSUE THREAD

**Issue by benirose** [punkave/apostrophe#319]
We try not to use h1 tags in our widget markup and it's good semantics to only have one on the page. We should update the widget markup to use a different tag. Probably too late for the BC break headache it might cause in 0.5, but definitely doable in 0.6.

**Comment by boutell** [comment]
Yes, that's a major faux pas.

We could introduce a slideshowTitleTag option in 0.5 if it's bugging you
now.

On Wed, Jul 29, 2015 at 11:48 AM, benirose <notifications@github.com> wrote:

> We try not to use h1 tags in our widget markup and it's good semantics to
> only have one on the page. We should update the widget markup to use a
> different tag. Probably too late for the BC break headache it might cause
> in 0.5, but definitely doable in 0.6.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/319>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
We are reimplementing these from templates from scratch, so this becomes a nonfunctional requirement.
