### ISSUE TITLE
html file in the public folder showing 404 error

### ISSUE THREAD

**Issue by Danny-weebo** [punkave/apostrophe#325]
I'm trying to upload a file for webmaster tools, a short .html file with a string inside. I put it in the public folder, but when I try to access it via the browser it takes me to a 404 error page. I tried setting permissions to 777, and verified the ownership of the file, nothing helps. Any ideas?

@israelidanny 
thanks.

**Comment by boutell** [comment]
Just tried this. It works. Do not add /public to the URL, maybe that's what
you're doing?

On Thu, Aug 13, 2015 at 8:58 AM, Danny Braunstein <notifications@github.com>
wrote:

> I'm trying to upload a file for webmaster tools, a short .html file with a
> string inside. I put it in the public folder, but when I try to access it
> via the browser it takes me to a 404 error page. I tried setting
> permissions to 777, and verified the ownership of the file, nothing helps.
> Any ideas?
>
> thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/325>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
Also think about anything you might have done in your nginx or other front end proxy configuration that could thwart this, but that's probably not it as you'd have trouble accessing any of Apostrophe's static assets.
