### ISSUE TITLE
Admin bar menu should be behind modals

### ISSUE THREAD

**Issue by marti1125** [punkave/apostrophe#326]
I am using Firefox. It happend in the demo
<img width="729" alt="screen shot 2015-08-15 at 01 27 28" src="https://cloud.githubusercontent.com/assets/223240/9287775/1909306e-42ed-11e5-9e85-f2c5e77bd3dc.png">

**Comment by boutell** [comment]
It looks like you have the media library modal open at this point? I think
the bug in this case is that you can access anything but the media library
modal at all until you're done with it. Thanks for reporting that there's a
UX problem here, in any event!

On Sat, Aug 15, 2015 at 2:30 AM, Willy Aguirre <notifications@github.com>
wrote:

> I am using Firefox
> [image: screen shot 2015-08-15 at 01 27 28]
> <https://cloud.githubusercontent.com/assets/223240/9287775/1909306e-42ed-11e5-9e85-f2c5e77bd3dc.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/326>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
tagging refactor but we might consider an 0.5 backport. It's a bug really

**Comment by jth-** [comment]
Fixed
