### ISSUE TITLE
Create consistency between area widgets and singletons

### ISSUE THREAD

**Issue by benirose** [punkave/apostrophe#345]
It would seem an area widget that is empty gets an `apos-empty` class on it. The div also gets a class of the widget name. Singletons don't get either, just a `data-type` property. Would be good to pick a pattern that exposes the most information in the best way and make sure they both implement the same pattern.

**Comment by benirose** [comment]
Further issues arise in that an empty area widget will keep it's height for controls when empty and editable, but collapse completely when not editable. This doesn't seem to be the case with singletons, as they also are missing any classes signifying if they are editable.

**Comment by jth-** [comment]
The effort to solve this is being performed in issue #380, closing duplicate.
