### ISSUE TITLE
Pieces: pieces is calling self.newInstance which doesn't seem to exist, yet not crashing, what's the story?

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe#381]
This ought to be a method that calls schemas.newInstance.

**Comment by jth-** [comment]
The `afterConstruct` has this line:
```js
_.defaults(self, self.manager);
```
Which essentially adds the default docs manager to pieces, which includes a `newInstance` definition that calls `schemas.newInstance`. This seems to work, going to close this, but let me know if you don't find this explanation satisfactory @boutell
