### ISSUE TITLE
If a page is moved to the trash, its slug should always change, even if it has been edited

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe#385]
Normally, Apostrophe leaves user-customized slugs alone when changing the parent of a page. However, the trash can should be an exception to this rule. Otherwise, the trashed page continues to block the reuse of its slug by a new page, which is frustrating.

**Comment by warent** [comment]
I've encountered this issue :(

**Comment by boutell** [comment]
This has been resolved.
