### ISSUE TITLE
Storing Video HTML from Oembed response locally

### ISSUE THREAD

**Issue by mcrider** [punkave/apostrophe#386]
in public/js/widgets/editors/video.js, I think it would be really helpful to store the 'html' in the response from Oembed in the local MongoDB.  I have a video library interface and requiring the call to oembed seems to basically triple the number of requests -- One to call /apos/oembed, oembed's call to the video's URL (e.g. youtube), then the iframe's request for the video.  It would be a lot more efficient if the iframe html was just stored locally and I could grab that.

**Comment by boutell** [comment]
oembed responses are cached by Apostrophe for one hour, so we don't hit the actual backend oembed services over and over.
