### ISSUE TITLE
"min" and "max" "enforced" on browser side only right now for strings

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe#389]
Schemas should truly enforce these on the server side, the only place it counts. The browser side UI is of course very helpful for well intentioned users. Both 0.5 and 0.6.

**Comment by jth-** [comment]
Broke off the `0.6` version of this issue. Note that this change might be exclusively in `apostrophe-schemas` in 0.5.

**Comment by boutell** [comment]
This was implemented.
