### ISSUE TITLE
Adding autoprefixer

### ISSUE THREAD

**Issue by jacobdubail** [punkave/apostrophe#391]
I'd like to use sass and a custom build script so I can use autoprefixer and other tools. 

Do I need to do this outside of the Apostrophe's build system? 

Do I just need to install gulp and sass the way I would in any other project, then load up my compiled css via the "assets" property in app.js?

Thanks!

**Comment by jsumnersmith** [comment]
Hey Jacob, 

You've got two options as far as adding assets:
* 1. You can use Gulp and Sass to create compiled CSS files and simply add them to the `assets` option in `app.js`. This will allow your files to take advantage of the minification in Apostorphe's build process. 
* 2. If you want to handle your own minification, you can add a new directory in the top-level `public` directory as anything in there is served there at the base url (i.e. `yoursite.com/css`, `youssite.com/js` or `yourtsite.com/your-new-directory`). Then simply link to your compiled stylesheet as you would typically do in another project.

Let me know if that helps!

**Comment by boutell** [comment]
Closing for hygiene, but let us know if you have further questions!
