### ISSUE TITLE
Modals could be opened several times

### ISSUE THREAD

**Issue by szdmInteraktiv** [punkave/apostrophe#392]
It is possible to open a modal in the main-menu serveral times. For example one could open `new users` and after that `manage users`. Further more you could open the *same* modal several times!

This is a big problem for editors. For example the open an edit-modal accidentally two times. In the modal on top they change something and hit the `save` button. After that they wonder about the second modal and hit `save` again. The changes obviously are not saved, because old settings are saved after new settings.

<img width="1002" alt="bildschirmfoto 2015-12-08 um 16 09 13" src="https://cloud.githubusercontent.com/assets/16136513/11658969/2149a446-9dc6-11e5-8c7f-e0579874dc70.png">

**Comment by boutell** [comment]
This has been fixed by new versions of the "apostrophe" and
"apostrophe-ui-2" modules.

The arc of apostrophe is long, but it bends toward usability.

On Tue, Dec 8, 2015 at 10:13 AM, szdmInteraktiv <notifications@github.com>
wrote:

> It is possible to open a modal in the main-menu serveral times. For
> example one could open new users and after that manage users. Further
> more you could open the *same* modal several times!
>
> This is a big problem for editors. For example the open an edit-modal
> accidentally two times. In the modal on top they change something and hit
> the save button. After that they wonder about the second modal and hit
> save again. The changes obviously are not saved, because old settings are
> saved after new settings.
>
> [image: bildschirmfoto 2015-12-08 um 16 09 13]
> <https://cloud.githubusercontent.com/assets/16136513/11658969/2149a446-9dc6-11e5-8c7f-e0579874dc70.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/392>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by szdmInteraktiv** [comment]
Hello @boutell, thanks for your response. I tried it again with the newest packages i think, but it is still possible to open the modal two times.

Theses are the versions we installed:

```
➜  phoenix git:(develop) ✗ npm ls --depth 1 | grep apostrophe
├─┬ apostrophe-blog-2@0.5.59
├─┬ apostrophe-browserify@0.5.8
├─┬ apostrophe-editor-2@0.5.49
├─┬ apostrophe-fancy-page@0.5.18
├─┬ apostrophe-groups@0.5.33
├─┬ apostrophe-people@0.5.55
├─┬ apostrophe-schema-widgets@0.5.21
├─┬ apostrophe-site@0.5.46
│ ├── apostrophe@0.5.347
│ ├── apostrophe-pages@0.5.85
│ ├── apostrophe-schemas@0.5.79
├─┬ apostrophe-snippets@0.5.84
│ ├── apostrophe-schemas@0.5.79
├─┬ apostrophe-ui-2@0.5.58
```

`npm outdated --depth 1` does also not show that `apostrophe` or `apostrophe-site` is outdated.

Screenshots:
This is while the the first modal is open. I click on the button again and then the overlay is opened twice:
![bildschirmfoto 2015-12-16 um 13 53 23](https://cloud.githubusercontent.com/assets/16136513/11841280/835a0dc4-a3fc-11e5-8ac5-98f1e65afa5c.png)

Here we can see that there are two modals:
![bildschirmfoto 2015-12-16 um 14 07 52](https://cloud.githubusercontent.com/assets/16136513/11841567/73433436-a3fe-11e5-8266-0175c9d5b351.png)

Are we doing something wrong? 

Thanks in advance again!

**Comment by boutell** [comment]
I can't even get there; the admin bar is grayed out now as it should be:

https://dl.dropboxusercontent.com/spa/jfyjetktfp495r1/7vjy2a6b.png

I'm trying out the sandbox with a fresh npm install to be sure though.



On Wed, Dec 16, 2015 at 8:41 AM, szdmInteraktiv <notifications@github.com>
wrote:

> Hello @boutell <https://github.com/boutell>, thanks for your response. I
> tried it again with the newest packages i think, but it is still possible
> to open the modal two times.
>
> Theses are the versions we installed:
>
> ➜  phoenix git:(develop) ✗ npm ls --depth 1 | grep apostrophe
> ├─┬ apostrophe-blog-2@0.5.59
> ├─┬ apostrophe-browserify@0.5.8
> ├─┬ apostrophe-editor-2@0.5.49
> ├─┬ apostrophe-fancy-page@0.5.18
> ├─┬ apostrophe-groups@0.5.33
> ├─┬ apostrophe-people@0.5.55
> ├─┬ apostrophe-schema-widgets@0.5.21
> ├─┬ apostrophe-site@0.5.46
> │ ├── apostrophe@0.5.347
> │ ├── apostrophe-pages@0.5.85
> │ ├── apostrophe-schemas@0.5.79
> ├─┬ apostrophe-snippets@0.5.84
> │ ├── apostrophe-schemas@0.5.79
> ├─┬ apostrophe-ui-2@0.5.58
>
> npm outdated --depth 1 does also not show that apostrophe or
> apostrophe-site is outdated.
>
> Screenshots:
> This is while the the first modal is open. I click on the button again and
> then the overlay is opened twice:
> [image: bildschirmfoto 2015-12-16 um 13 53 23]
> <https://cloud.githubusercontent.com/assets/16136513/11841280/835a0dc4-a3fc-11e5-8ac5-98f1e65afa5c.png>
>
> Here we can see that there are two modals:
> [image: bildschirmfoto 2015-12-16 um 14 07 52]
> <https://cloud.githubusercontent.com/assets/16136513/11841567/73433436-a3fe-11e5-8266-0175c9d5b351.png>
>
> Are we doing something wrong?
>
> Thanks in advance again!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/392#issuecomment-165108689>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
I just tried this with a fresh npm install of the latest packages, nothing
linked. It works correctly. Possibly you're looking at cached CSS somehow.

On Wed, Dec 16, 2015 at 8:54 AM, Tom Boutell <tom@punkave.com> wrote:

> I can't even get there; the admin bar is grayed out now as it should be:
>
> https://dl.dropboxusercontent.com/spa/jfyjetktfp495r1/7vjy2a6b.png
>
> I'm trying out the sandbox with a fresh npm install to be sure though.
>
>
>
> On Wed, Dec 16, 2015 at 8:41 AM, szdmInteraktiv <notifications@github.com>
> wrote:
>
>> Hello @boutell <https://github.com/boutell>, thanks for your response. I
>> tried it again with the newest packages i think, but it is still possible
>> to open the modal two times.
>>
>> Theses are the versions we installed:
>>
>> ➜  phoenix git:(develop) ✗ npm ls --depth 1 | grep apostrophe
>> ├─┬ apostrophe-blog-2@0.5.59
>> ├─┬ apostrophe-browserify@0.5.8
>> ├─┬ apostrophe-editor-2@0.5.49
>> ├─┬ apostrophe-fancy-page@0.5.18
>> ├─┬ apostrophe-groups@0.5.33
>> ├─┬ apostrophe-people@0.5.55
>> ├─┬ apostrophe-schema-widgets@0.5.21
>> ├─┬ apostrophe-site@0.5.46
>> │ ├── apostrophe@0.5.347
>> │ ├── apostrophe-pages@0.5.85
>> │ ├── apostrophe-schemas@0.5.79
>> ├─┬ apostrophe-snippets@0.5.84
>> │ ├── apostrophe-schemas@0.5.79
>> ├─┬ apostrophe-ui-2@0.5.58
>>
>> npm outdated --depth 1 does also not show that apostrophe or
>> apostrophe-site is outdated.
>>
>> Screenshots:
>> This is while the the first modal is open. I click on the button again
>> and then the overlay is opened twice:
>> [image: bildschirmfoto 2015-12-16 um 13 53 23]
>> <https://cloud.githubusercontent.com/assets/16136513/11841280/835a0dc4-a3fc-11e5-8ac5-98f1e65afa5c.png>
>>
>> Here we can see that there are two modals:
>> [image: bildschirmfoto 2015-12-16 um 14 07 52]
>> <https://cloud.githubusercontent.com/assets/16136513/11841567/73433436-a3fe-11e5-8266-0175c9d5b351.png>
>>
>> Are we doing something wrong?
>>
>> Thanks in advance again!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/apostrophe/issues/392#issuecomment-165108689>
>> .
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by szdmInteraktiv** [comment]
Ah i see. Yes i just checked out the sandbox and now it works. I think this is a problem with our setup and z-index. Thanks a lot for your fast response.

**Comment by boutell** [comment]
No problem. A lot of people probably have some overrides of their own for
this, but you can use our new changes as a guide.

On Wed, Dec 16, 2015 at 9:14 AM, szdmInteraktiv <notifications@github.com>
wrote:

> Ah i see. Yes i just checked out the sandbox and now it works. I think
> this is a problem with our setup and z-index. Thanks a lot for your fast
> response.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/392#issuecomment-165119399>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
