### ISSUE TITLE
Best way to get the Mongo _ID

### ISSUE THREAD

**Issue by rwatts3** [punkave/apostrophe#393]
What is the best way to use the Mongo _ID. I am building a shopping cart and PayPal checkout experience for my client.  And I would like to assign the Mongo ID as a data attribute so I can pull that data into the check out or  shopping card view of the process.  I would fetch the details for the product upon rendering the shopping cart this way I only have to pass around the I'd rather than the full product

**Comment by boutell** [comment]
The _id property is available on all snippets, pages, etc. in Apostrophe.
Maybe you should clarify exactly what kind of object you're asking about.

On Fri, Dec 11, 2015 at 12:41 PM, Ryan Watts <notifications@github.com>
wrote:

> What is the best way to use the Mongo _ID. I am building a shopping cart
> and PayPal checkout experience for my client. And I would like to assign
> the Mongo ID as a data attribute so I can pull that data into the check out
> or shopping card view of the process. I would fetch the details for the
> product upon rendering the shopping cart this way I only have to pass
> around the I'd rather than the full product
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/393>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by rwatts3** [comment]
That's great.  I probably went over boarding with the explanation.  I
suppose the general question is how do I access it from within the
template.

**Comment by boutell** [comment]
._id

(:

On Fri, Dec 11, 2015 at 2:38 PM, Ryan Watts <notifications@github.com>
wrote:

> That's great. I probably went over boarding with the explanation. I
> suppose the general question is how do I access it from within the
> template.
>
> On Fri, Dec 11, 2015, 11:53 AM Tom Boutell <notifications@github.com>
> wrote:
>
> > The _id property is available on all snippets, pages, etc. in Apostrophe.
> > Maybe you should clarify exactly what kind of object you're asking about.
> >
> > On Fri, Dec 11, 2015 at 12:41 PM, Ryan Watts <notifications@github.com>
> > wrote:
> >
> > > What is the best way to use the Mongo _ID. I am building a shopping
> cart
> > > and PayPal checkout experience for my client. And I would like to
> assign
> > > the Mongo ID as a data attribute so I can pull that data into the check
> > out
> > > or shopping card view of the process. I would fetch the details for the
> > > product upon rendering the shopping cart this way I only have to pass
> > > around the I'd rather than the full product
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/punkave/apostrophe/issues/393>.
> > >
> >
> >
> >
> > --
> >
> >
> > *THOMAS BOUTELL, *DEV & OPS
> > P'UNK AVENUE | (215) 755-1330 | punkave.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/punkave/apostrophe/issues/393#issuecomment-164016717
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/393#issuecomment-164029996>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
(That is, if the object in question is "page", it's "page._id")

On Fri, Dec 11, 2015 at 3:00 PM, Tom Boutell <tom@punkave.com> wrote:

> ._id
>
> (:
>
> On Fri, Dec 11, 2015 at 2:38 PM, Ryan Watts <notifications@github.com>
> wrote:
>
>> That's great. I probably went over boarding with the explanation. I
>> suppose the general question is how do I access it from within the
>> template.
>>
>> On Fri, Dec 11, 2015, 11:53 AM Tom Boutell <notifications@github.com>
>> wrote:
>>
>> > The _id property is available on all snippets, pages, etc. in
>> Apostrophe.
>> > Maybe you should clarify exactly what kind of object you're asking
>> about.
>> >
>> > On Fri, Dec 11, 2015 at 12:41 PM, Ryan Watts <notifications@github.com>
>> > wrote:
>> >
>> > > What is the best way to use the Mongo _ID. I am building a shopping
>> cart
>> > > and PayPal checkout experience for my client. And I would like to
>> assign
>> > > the Mongo ID as a data attribute so I can pull that data into the
>> check
>> > out
>> > > or shopping card view of the process. I would fetch the details for
>> the
>> > > product upon rendering the shopping cart this way I only have to pass
>> > > around the I'd rather than the full product
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/punkave/apostrophe/issues/393>.
>> > >
>> >
>> >
>> >
>> > --
>> >
>> >
>> > *THOMAS BOUTELL, *DEV & OPS
>> > P'UNK AVENUE | (215) 755-1330 | punkave.com
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/punkave/apostrophe/issues/393#issuecomment-164016717>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/apostrophe/issues/393#issuecomment-164029996>
>> .
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by rwatts3** [comment]
Ah , Thank you for the insight. 
Have you or anyone within the community managed to build shopping cart like functionality within Apostrophe ?

**Comment by boutell** [comment]
Not in A2 I think. Not that it's terribly difficult to integrate Paypal, Braintree, etc.
