### ISSUE TITLE
How to hide certain fields/groups to admin only?

### ISSUE THREAD

**Issue by rwatts3** [punkave/apostrophe#394]
Is it possible to hide a field and/or an entire group from non-admin users.
If I have the group of fields "Admin" or "Settings" I would like to hide the group altogether.

**Comment by jth-** [comment]
Hey @rwatts, if you look at `apostrophe-users`, the `profileFields` and `applyFields` both use the schema subset feature to provide specific routes for editing part of an object. That's probably the best code example of this at the moment.

Currently there isn't a way of doing this through configuration, but we'll add this to the backlog to consider for the future.

**Comment by boutell** [comment]
This is now a feature. You can set `permission: 'admin'` on any schema field. Other permissions work too.
