### ISSUE TITLE
Areas: Design considerations around area-level button overlap.

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe#400]
https://dl.dropboxusercontent.com/spa/jfyjetktfp495r1/rgpm5smr.png

I had to kill a man just to get to the point where I could type in a rich text widget.

**Comment by jth-** [comment]
@stuartromanek I know you've got some designs already for this, let me know if there's anything more information you need.

**Comment by jth-** [comment]
Some progress committed here, leaving open for now.

**Comment by jth-** [comment]
@stuartromanek Let's group up on this and check what still needs to change before the trainings over the next couple weeks.

**Comment by jth-** [comment]
Will continue to tweak, but the bulk of this is now merged in. More specific issues can address future needs.
