### ISSUE TITLE
[apostrophe-images] add cropping to chooser

### ISSUE THREAD

**Issue by mcoppola** [punkave/apostrophe#450]

**Comment by boutell** [comment]
I already implemented cropping. Did it go away?

**Comment by mcoppola** [comment]
Nope!  This issue is just for us to add + style cropping in the chooser controls.

**Comment by boutell** [comment]
Wait, this is now assigned to me, but according to you it never went away and this is just about changing icons. Isn't that better handled on your end?

**Comment by jth-** [comment]
Oh, I think I reassigned this when we were talking the other day. Is cropping currently supported in the chooser? I'm not sure the answer to that question, but I can look into it.

**Comment by jth-** [comment]
Cropping exists and works. Definitely needs some styling, but unassigning from @boutell

**Comment by jth-** [comment]
Merged this PR.
