### ISSUE TITLE
[apostrophe-images] manager can't save new image, or "replace" image

### ISSUE THREAD

**Issue by mcoppola** [punkave/apostrophe#452]

**Comment by boutell** [comment]
So you can't upload an image at all right now? Or you just can't upload a
replacement?

On Thu, Mar 3, 2016 at 9:25 AM, Matthew Coppola <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/452>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by mcoppola** [comment]
@boutell this was just a front-end bug introduced when we changed the "upload image" button.  closed with 6169e0b.
