### ISSUE TITLE
[areas] save failing on some page types - _doc "not found" in saveArea

### ISSUE THREAD

**Issue by mcoppola** [punkave/apostrophe#454]
I'm seeing this on the default page template, but not the home page or pieces pages.  The saveArea function in the areas api returns "notfound" for the `docId`.

**Comment by boutell** [comment]
Still hunting this? Need help?

**Comment by jth-** [comment]
I believe this is still happening, though I don't think either of us have taken the time to dig into it quite yet.

**Comment by boutell** [comment]
OK - just let me know if it gets hairy.

On Mon, Mar 14, 2016 at 10:13 AM, Jimmy Harrison <notifications@github.com>
wrote:

> I believe this is still happening, though I don't think either of us have
> taken the time to dig into it quite yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/454#issuecomment-196324558>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
@mcoppola I fixed an issue where areas on unpublished pages weren't getting saved due to a notfound error and I believe that may resolve this issue. Have you noticed this issue over the past couple days?

**Comment by jth-** [comment]
No longer seeing this issue.
