### ISSUE TITLE
error under windows platform

### ISSUE THREAD

**Issue by rcorzogutierrez** [punkave/apostrophe#469]
when
 `npm install` 
return 
`Failed at the apostrophe@0.5.370 prepublish script 'sh scripts/prepublish.sh'.`

**Comment by boutell** [comment]
Hmm, this should not be running at all since we're not publishing.

I'm going to remove this feature, it's causing agita.

On Tue, Mar 22, 2016 at 3:53 PM, rcorzogutierrez <notifications@github.com>
wrote:

> when
> npm install
> return
> Failed at the apostrophe@0.5.370 prepublish script 'sh
> scripts/prepublish.sh'.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/469>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
Gone. Try again.

**Comment by rcorzogutierrez** [comment]
I run and no error but there are warnings
`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8`

thank a lot
