### ISSUE TITLE
Database is empty after push on production, which leads to 404

### ISSUE THREAD

**Issue by eric-burel** [punkave/apostrophe#470]
Hello there,

I am trying to host an apostrophe project on Heroku. I have trouble setting up the database, it connects well and creates the tables, but does not fill them, see the mongolab report :

```
Collection    Nb of docs   Capped?   Size
aposCache	0	false	23.95 KB	
aposPages	0	false	143.72 KB	
aposRedirects	0	false	15.97 KB	
aposVersions	0	false	15.97 KB	
aposVideos	0	false	15.97 KB	
sessions	1	false	16.45 KB	
```
The session is set correctly, I can connect to the website. You can take a look : 
http://gratos.herokuapp.com
However, as there is no home page, I got a nice 404 and can not create a new page as the page management button does not appear on 404. 

I thought about two solutions :
- if there are no pages in the database, creates a default home page
- add page management menu on the 404 page

Yet I am not sure how to implement that. Do you have any other solution or did I miss something ?

Thanks

**Comment by boutell** [comment]
You want to run the apostrophe:reset task on your production server.

node app apostrophe:reset

That will give you an initial database to work with.

Or, you could copy your local mongo database to whatever mongo hosting you
are using (heroku doesn't come with mongo, you don't say what you're
using). That's a mongo thing though and not Apostrophe's job, per se.


On Wed, Mar 23, 2016 at 12:26 PM, eric-burel <notifications@github.com>
wrote:

> Hello there,
>
> I am trying to host an apostrophe project on Heroku. I have trouble
> setting up the database, it connects well and creates the tables, but does
> not fill them, see the mongolab report :
>
> Collection    Nb of docs   Capped?   Size
> aposCache   0   false   23.95 KB
> aposPages   0   false   143.72 KB
> aposRedirects   0   false   15.97 KB
> aposVersions    0   false   15.97 KB
> aposVideos  0   false   15.97 KB
> sessions    1   false   16.45 KB
>
> The session is set correctly, I can connect to the website. You can take a
> look :
> http://gratos.herokuapp.com
> However, as there is no home page, I got a nice 404 and can not create a
> new page as the page management button does not appear on 404.
>
> I thought about two solutions :
>
>    - if there are no pages in the database, creates a default home page
>    - add page management menu on the 404 page
>
> Yet I am not sure how to implement that. Do you have any other solution or
> did I miss something ?
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/470>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
