### ISSUE TITLE
[pieces] edit piece returning "unblessed"

### ISSUE THREAD

**Issue by mcoppola** [punkave/apostrophe#471]
I believe is happening after a widget or area of the piece is edited in context.

**Comment by mcoppola** [comment]
also returning this?  possibly not the same bug, but same symptoms 

/Users/matthew/src/apostrophe-06/lib/modules/apostrophe-areas/lib/routes.js:77
          return manager.load(req, [ widget ], callback);

**Comment by boutell** [comment]
Feel free to add more bless calls. It's pretty straightforward to use. The
idea is just to make sure that any combination of options that definitely
came from the developer (not the browser!) gets blessed before the browser
sends that combo back to re-render some widget or other.

On Fri, Mar 25, 2016 at 10:51 AM, Matthew Coppola <notifications@github.com>
wrote:

> also returning this? possibly not the same bug, but same symptoms
>
>
> /Users/matthew/src/apostrophe-06/lib/modules/apostrophe-areas/lib/routes.js:77
> return manager.load(req, [ widget ], callback);
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/471#issuecomment-201320608>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
