### ISSUE TITLE
Does not install

### ISSUE THREAD

**Issue by JemiloII** [punkave/apostrophe#474]
Centos 7
Attempted with node 0.12, 4.4.1, and 5.91
npm v2, and v3

It constantly kills itself during install. It's rather annoying, apostrophe-site never installs.

i have all the dependencies installed to build, gcc, make, etc.

Even attempted to follow this guide http://apostrophenow.org/howtos/production.html#system-requirements.

Using apostrophe-cli to create a new project, cd into, and npm install

**Comment by JemiloII** [comment]
i attempted the sandbox package.json
script is killed at extract:apostrophe-ui-2

**Comment by boutell** [comment]
Please be specific. Is this an npm install error?

We really don't control npm, but I suggest upgrading it to latest stable:

sudo npm install -g npm

Again though... npm is not our baby.

Hope this is of some help!

On Sun, Mar 27, 2016 at 2:32 AM, Brian M. Jemilo II <
notifications@github.com> wrote:

> i attempted the sandbox package.json
> script is killed at extract:apostrophe-ui-2
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/474#issuecomment-202000782>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
You could be running out of RAM. Is this on a fairly small VPS perhaps? I
know npm has been RAM-hungry lately.

On Sun, Mar 27, 2016 at 8:43 AM, Tom Boutell <tom@punkave.com> wrote:

> Please be specific. Is this an npm install error?
>
> We really don't control npm, but I suggest upgrading it to latest stable:
>
> sudo npm install -g npm
>
> Again though... npm is not our baby.
>
> Hope this is of some help!
>
> On Sun, Mar 27, 2016 at 2:32 AM, Brian M. Jemilo II <
> notifications@github.com> wrote:
>
>> i attempted the sandbox package.json
>> script is killed at extract:apostrophe-ui-2
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/apostrophe/issues/474#issuecomment-202000782>
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by JemiloII** [comment]
So far yes, it is an npm install error. hmmm, ram.. i haven't thought about that, I will check that out. Thanks!

**Comment by JemiloII** [comment]
Ah ha, npm is evil. 1.5GB of ram was needed to install... like oly cow lol. I guess i'll have to setup a build system.

**Comment by boutell** [comment]
That is kind of a bummer. Was mongo running on the system or something? Or was it 1.5GB just for npm? Not that npm is something we control, but it does make you long for an alternative, doesn't it.

**Comment by JemiloII** [comment]
I made sure that mongo and docker were not running at the time of the install. Just node v 4.1.1. Hopefully npm can fix the memory issues. That's a lotta memory being consumed. I wonder if it has anything to do with gcc compiling certain modules.

**Comment by boutell** [comment]
My suspicion is not... I think our introduction of babel into our
apostrophe-browserify stack may be creating new challenges for it. Although
I find tons of memory being consumed by npm installs unrelated to
apostrophe as well.


On Wed, Mar 30, 2016 at 2:59 PM, Brian M. Jemilo II <
notifications@github.com> wrote:

> I made sure that mongo and docker were not running at the time of the
> install. Just node v 4.1.1. Hopefully npm can fix the memory issues. That's
> a lotta memory being consumed. I wonder if it has anything to do with gcc
> compiling certain modules.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/474#issuecomment-203583071>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
