### ISSUE TITLE
Global 'page' doesn't exist by default.

### ISSUE THREAD

**Issue by jth-** [punkave/apostrophe#479]
Should a page with a slug 'global' be parked by default?

**Comment by boutell** [comment]
I'd say it should be, and that there should be a loader to pull it into a
normal pageServe situation, and also an easy way to call that loader from
other situations, like a notfound page...

On Tue, Mar 29, 2016 at 12:50 PM, Jimmy Harrison <notifications@github.com>
wrote:

> Should a page with a slug 'global' be parked by default?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/479>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
In fact I'd say it should be straight-up middleware

On Tue, Mar 29, 2016 at 12:51 PM, Tom Boutell <tom@punkave.com> wrote:

> I'd say it should be, and that there should be a loader to pull it into a
> normal pageServe situation, and also an easy way to call that loader from
> other situations, like a notfound page...
>
> On Tue, Mar 29, 2016 at 12:50 PM, Jimmy Harrison <notifications@github.com
> > wrote:
>
>> Should a page with a slug 'global' be parked by default?
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/apostrophe/issues/479>
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
It shouldn't be part of the normal parking API I think. It's a pretty
special case, you always want one. The docs module could take care of it,
but it would be cleanest to have an apostrophe-global-doc module.

On Tue, Mar 29, 2016 at 12:51 PM, Tom Boutell <tom@punkave.com> wrote:

> In fact I'd say it should be straight-up middleware
>
> On Tue, Mar 29, 2016 at 12:51 PM, Tom Boutell <tom@punkave.com> wrote:
>
>> I'd say it should be, and that there should be a loader to pull it into a
>> normal pageServe situation, and also an easy way to call that loader from
>> other situations, like a notfound page...
>>
>> On Tue, Mar 29, 2016 at 12:50 PM, Jimmy Harrison <
>> notifications@github.com> wrote:
>>
>>> Should a page with a slug 'global' be parked by default?
>>>
>>> —
>>> You are receiving this because you are subscribed to this thread.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/punkave/apostrophe/issues/479>
>>>
>>
>>
>>
>> --
>>
>>
>> *THOMAS BOUTELL, *DEV & OPS
>> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
Makes sense to me. Currently there is an `apostrophe-global` module that fetches it on `pageServe`, it's just not created anywhere. My current workaround is to park a global page at project-level.

**Comment by jth-** [comment]
Resolved by #547
