### ISSUE TITLE
Menu with images

### ISSUE THREAD

**Issue by janaobzerova** [punkave/apostrophe#480]
Hi, 
I used "apostrophe-fancy-page" and I add field "promoPhoto" (singleton, slideshow) to my page template. I want to use this image in list, but {{ aposSingleton({ area: page.promoPhoto, type: 'slideshow' }) }} does not works. 

app.js
```
dog: {
        extend: 'apostrophe-fancy-page',
        name: 'dog',
        label: 'Detail psa',
        addFields: [{
            name: 'bitch',
            label: 'Fena',
            type: 'boolean'
        },
        {
            name: 'promoPhoto',
            label: 'Fotka',
            type: 'singleton',
            widgetType: 'slideshow',
            options: {
                limit: 1
            }
        }]
    }
```

dogs.html
```
<ul class="dogs-list">
    {% for child in page.children %}
        <li class="dog">
            {{ aposSingleton({ area: child.promoPhoto, type: 'slideshow' }) }}
            <a href="{{ child.url }}">{{ child.title }}</a>
        </li>
    {% endfor %}
</ul>
```

**Comment by boutell** [comment]
You've got the right idea, but when Apostrophe fetches child pages for
convenience in building the nav, it doesn't load related resources for all
of their areas/singletons/widgets by default, for performance reasons.
Normally the nav doesn't need them.

You can adjust your settings in app.js for the "pages" key:

{
  ... other stuff ...
  pages: {
    ... other stuff ...
    descendantOptions: { areas: [ 'promoPhoto' ] }
  }
}



On Sat, Apr 2, 2016 at 1:15 PM, janaobzerova <notifications@github.com>
wrote:

> Hi,
> I used "apostrophe-fancy-page" and I add field "promoPhoto" (singleton,
> slideshow) to my page template. I want to use this image in list, but {{
> aposSingleton({ area: page.promoPhoto, type: 'slideshow' }) }} does not
> works.
>
> app.js
>
> dog: {
>         extend: 'apostrophe-fancy-page',
>         name: 'dog',
>         label: 'Detail psa',
>         addFields: [{
>             name: 'bitch',
>             label: 'Fena',
>             type: 'boolean'
>         },
>         {
>             name: 'promoPhoto',
>             label: 'Fotka',
>             type: 'singleton',
>             widgetType: 'slideshow',
>             options: {
>                 limit: 1
>             }
>         }]
>     }
>
> dogs.html
>
> <ul class="dogs-list">
>     {% for child in page.children %}
>         <li class="dog">
>             {{ aposSingleton({ area: child.promoPhoto, type: 'slideshow' }) }}
>             <a href="{{ child.url }}">{{ child.title }}</a>
>         </li>
>     {% endfor %}
> </ul>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/480>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
