### ISSUE TITLE
apos-middle & item.position

### ISSUE THREAD

**Issue by ehibes** [punkave/apostrophe#485]
Hi, 

Why did apostrophe add a apos-middle class on each editable areas? It seems that it's defined by item's position property.
But how to change this value to left for instance to match with my original layout design?

Thanks in advance.

**Comment by boutell** [comment]
These are anachronisms left over from an earlier approach to widgets in
Apostrophe. They will be gone in 0.6. Sorry for the annoyance. You should
ignore these.

If your goal is to control the alignment of widgets, you should look at the
lockups feature:

http://apostrophenow.org/tutorials/frontend-development/working-with-lockups.html



On Thu, Apr 7, 2016 at 11:46 AM, ehibes <notifications@github.com> wrote:

> Hi,
>
> Why did apostrophe add a apos-middle class on each editable area? It seems
> that it's defined by item's position property.
> But how to change this value to left for instance to match with my
> original layout design?
>
> Thanks in advance.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/485>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
