### ISSUE TITLE
Locale in url

### ISSUE THREAD

**Issue by ehibes** [punkave/apostrophe#490]
Hi,

To do multi-language in my website, I need to put locale on the url, as slug prefix.
How I can do that? 
```
http://www.mydomain.com/fr/blog
http://www.mydomain.com/en/blog
```

**Comment by boutell** [comment]
Check this out:

https://www.npmjs.com/package/apostrophe-localization

On Sat, Apr 9, 2016 at 9:44 AM, ehibes <notifications@github.com> wrote:

> Hi,
>
> To do multi-language in my website, I need to put locale on the url, as
> slug prefix.
> How I can do that?
>
> http://www.mydomain.com/fr/bloghttp://www.mydomain.com/en/blog
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/490>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by ehibes** [comment]
Yes I use this module, but it doesn't change url to put the locale value. I mean that a page with unique slug can be in many languages, and it's not good for SEO.

**Comment by boutell** [comment]
The module supports starting the URL with the locale.

On Sat, Apr 9, 2016 at 10:44 AM, ehibes <notifications@github.com> wrote:

> Yes I use this module, but it doesn't change url to put the locale value.
> I mean that a page with unique slug can be in many languages, and it's not
> good for SEO.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/490#issuecomment-207798334>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by ehibes** [comment]
Yes but how to force to always use the prefix in url? I started to make a loader in app.js to get current locale, but it didn't work. Do you have any idea to make this?

**Comment by boutell** [comment]
The locale is available from req.locale thanks to the middleware. You
should be able to look at that, look at the URL to see that it does not
start with the desired prefix, and redirect.

On Sat, Apr 9, 2016 at 10:52 AM, ehibes <notifications@github.com> wrote:

> Yes but how to force to always use the prefix in url? I started to make a
> loader in app.js to get current locale, but it didn't work. Do you have any
> idea to make this?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/490#issuecomment-207800343>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by ehibes** [comment]
I make this two middleware functions
### 1. redirect homepage
```
    function(req, res, next) {
      if (req.url === '/') {
        res.redirect('/'+req.locale+'/');
      }
      next();
    },
```
This func causes the following error  : `Error: write after end` 
If I put compress to false in app.js it's ok, it seems to be an error with express compression and redirect.

### 2. redirect all pages without locale
 ```
    function(req, res, next) {
      // if not asset and not prefixed by lang redirect with localized url
      if (/^\/(css|js|eu|apos.*|fr)\//.test(req.url) === false) {
        res.redirect('/'+req.locale+req.url);
      }
      next();
    },
```
I've overwritten apostrophe-localization to define those middleware functions in index.js file.

**Comment by boutell** [comment]
Hi Ehibes, what's happening in both cases is a common async programming
error.

You are invoking res.direct but then your code keeps on running and still
calls next(). So your response object tries to do both things and bad
things happen (:

You want:

return res.redirect(whatever...)

Always Be Returning (ABR) when you write async functions.

Hope this is helpful!

On Tue, Apr 12, 2016 at 5:07 AM, ehibes <notifications@github.com> wrote:

> I make this two middleware functions
> 1. redirect homepage
>
>     function(req, res, next) {
>       if (req.url === '/') {
>         res.redirect('/'+req.locale+'/');
>       }
>       next();
>     },
>
> This func causes the following error : Error: write after end
> If I put compress to false in app.js it's ok, it seems to be an error with
> express compression and redirect.
> 2. redirect all pages without locale
>
>     function(req, res, next) {
>       // if not asset and not prefixed by lang redirect with localized url
>       if (/^\/(css|js|eu|apos.*|fr)\//.test(req.url) === false) {
>         res.redirect('/'+req.locale+req.url);
>       }
>       next();
>     },
>
> I've overwritten apostrophe-localization to define those middleware
> functions in index.js file.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/490#issuecomment-208805314>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by ehibes** [comment]
Thanks a lot, it works.
