### ISSUE TITLE
Slideshow singleton not accessible in page object

### ISSUE THREAD

**Issue by coreytegeler** [punkave/apostrophe#495]
I'm attempting to add an image to a page type using a `singleton` set to the `slideshow` `widgetType`

The interface is working fine (I can upload an image and the limit value works), but I cannot access the object in the templates

I am logging the page object with the below script in the page template, every other custom field works fine, just not the slideshow widget. 

    var data = {{ page | json }};
    console.log(data);

Here is what is set in app.js

    project: {
      extend: 'apostrophe-fancy-page',
      name: 'project',
      label: 'Project',
      addFields: [
        {
          name: 'thumb',
          label: 'Thumbnail',
          type: 'singleton',
          widgetType: 'slideshow',
          options: {
            limit: 1
          }
        }
      ]
    }

Any advice on how I can get this image in the template?

**Comment by boutell** [comment]
This works... I suspect there's something you're not mentioning, for
instance that you're not actually viewing the page itself, but a parent of
it, and want the thumbnail to appear in navigation?

On Tue, Apr 12, 2016 at 10:19 AM, Corey Tegeler <notifications@github.com>
wrote:

> I'm attempting to add an image to a page type using a singleton set to
> the slideshow widgetType
>
> The interface is working fine (I can upload an image and the limit value
> works), but I cannot access the object in the templates
>
> I am logging the page object with the below script in the page template,
> every other custom field works fine, just not the slideshow widget.
>
> var data = {{ page | json }};
> console.log(data);
>
> Here is what is set in app.js
>
> project: {
>   extend: 'apostrophe-fancy-page',
>   name: 'project',
>   label: 'Project',
>   addFields: [
>     {
>       name: 'thumb',
>       label: 'Thumbnail',
>       type: 'singleton',
>       widgetType: 'slideshow',
>       options: {
>         limit: 1
>       }
>     }
>   ]
> }
>
> Any advice on how I can get this image in the template?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/495>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by coreytegeler** [comment]
Correct! I'm trying to build a directory page of all of the children with thumbnails.

**Comment by boutell** [comment]
Please see:

http://apostrophenow.org/tutorials/frontend-development/navigation.html

The last heading here covers how to do this.

On Wed, Apr 13, 2016 at 10:29 AM, Corey Tegeler <notifications@github.com>
wrote:

> Correct! I'm trying to build a directory page of all of the children with
> thumbnails.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/495#issuecomment-209474452>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by coreytegeler** [comment]
I had the `descendantOptions` setup from this page before, but I was not using it correctly.

I was using `areas: ['slideshow', 'singleton']` instead of the name given to my custom field (i.e. `areas: [ 'thumb']`)

**Comment by boutell** [comment]
Makes sense.
