### ISSUE TITLE
[apostrophe-images] Namespace slugs of images and other piece types that aren't truly pagey, so they don't bump true pages to sloppy slugs.

### ISSUE THREAD

**Issue by jth-** [punkave/apostrophe#499]

**Comment by boutell** [comment]
Hmm. In what scenario does this happen? Either the filenames are crap, in
which case they would never conflict with the title of a blog post (for
example), or the filenames are awesome, in which case they... could
conflict if the image is titled "the gang at Marty's" and so is the
article, but still, pretty rare...

The prefix should still be reasonably friendly, in case somebody does
decide to build pieces-pages for images as a gallery.

On Wed, Apr 13, 2016 at 2:17 PM, Jimmy Harrison <notifications@github.com>
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/499>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
Thinking about things like people profiles or place show pages. For example, if John Smith has a profile, it's not unreasonable to think someone might upload `John Smith.jpg`. Both get the `john-smith` slug, and if the person created the image through the chooser while creating the chooser, the image will nab the first one, and the actual profile page will be something like `john-smith1`

**Comment by boutell** [comment]
Yeah, fair enough. I see no harm in your suggestion that there be a prefix.

On Thu, Apr 14, 2016 at 8:48 AM, Jimmy Harrison <notifications@github.com>
wrote:

> Thinking about things like people profiles or place show pages. For
> example, if John Smith has a profile, it's not unreasonable to think
> someone might upload John Smith.jpg. Both get the john-smith slug, and if
> the person created the image through the chooser while creating the
> chooser, the image will nab the first one, and the actual profile page will
> be something like john-smith1
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/499#issuecomment-209923494>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
Just realized one other case where this optional prefix could be useful: Users. Since generally, we are aiming to separate users and profiles, but I would say it's likely that a user also could have a profile. Some generalized slug-prefixing-mechanism for pieces could be useful.

Just capturing this thought here to remember it when it comes to implementation.
