### ISSUE TITLE
[apostrophe-images] Chooser template needs search ability/filters

### ISSUE THREAD

**Issue by jth-** [punkave/apostrophe#500]

**Comment by boutell** [comment]
I think you mean the manager template? But doesn't it have those things
already?

The chooser is only displaying what has already been chosen so pagination
is not an issue?

On Wed, Apr 13, 2016 at 4:23 PM, Jimmy Harrison <notifications@github.com>
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/500>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
Specifically talking about the images chooser here, and there is currently an issue with filters displaying on managers which are slidable (like choosers). The idea is to eventually have bottomless hooked up on the images manager. Maybe these are separate issues though.

**Comment by boutell** [comment]
Okay, that makes sense. Just making sure the chooser wasn't escaping its
intended scope (:

On Thu, Apr 14, 2016 at 10:59 AM, Jimmy Harrison <notifications@github.com>
wrote:

> Specifically talking about the images chooser here, and there is currently
> an issue with filters displaying on managers which are slidable (like
> choosers). The idea is to eventually have bottomless hooked up on the
> images manager. Maybe these are separate issues though.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/500#issuecomment-209987066>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
@mcoppola I've currently implemented a stopgap here by bringing traditional paging back in the grid view of images. Unless you particularly need filtering for your training, I think I'll probably this one back a sprint in order to prioritize other issues, is that cool?
