### ISSUE TITLE
[areas] receiving "unblessed" error when editing widgets

### ISSUE THREAD

**Issue by mcoppola** [punkave/apostrophe#511]
Is only happening on staging version of science-center. 

Possible cause is the server stoping and starting again since widget was created or last edited.

**Comment by boutell** [comment]
Hmm, blessings live in the session. If your login is surviving, then they
should too...

On Sat, Apr 16, 2016 at 4:29 PM, Matthew Coppola <notifications@github.com>
wrote:

> Possible cause is the server stoping and starting again since widget was
> created or last edited.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/511>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by mcoppola** [comment]
I have not seen this bug since.

**Comment by jth-** [comment]
Currently not reproducible, moving to backlog until then.

**Comment by jth-** [comment]
This is no longer reproducible, most likely fixed by various changes to area editing. Closing.
