### ISSUE TITLE
[apostrophe-alerts] Design an alternative for default javascript 'alert' and 'confirm' dialogs.

### ISSUE THREAD

**Issue by jth-** [punkave/apostrophe#512]
To be used for 'Unsaved Changes' dialogs, etc.

**Comment by boutell** [comment]
YUSSSS

On Mon, Apr 18, 2016 at 9:56 AM, Jimmy Harrison <notifications@github.com>
wrote:

> To be used for 'Unsaved Changes' dialogs, etc.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/512>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by stuartromanek** [comment]
<img width="1430" alt="screen shot 2016-04-21 at 2 59 10 pm" src="https://cloud.githubusercontent.com/assets/1889830/14721000/1c410df6-07d2-11e6-9fe7-2425d4476863.png">

**Comment by stuartromanek** [comment]
<img width="1427" alt="screen shot 2016-04-21 at 3 03 07 pm" src="https://cloud.githubusercontent.com/assets/1889830/14721016/2ea13f3e-07d2-11e6-8e3f-ac2262388346.png">

**Comment by boutell** [comment]
V. nice

On Thu, Apr 21, 2016 at 3:03 PM, Stuart Romanek <notifications@github.com>
wrote:

> [image: screen shot 2016-04-21 at 3 03 07 pm]
> <https://cloud.githubusercontent.com/assets/1889830/14721016/2ea13f3e-07d2-11e6-8e3f-ac2262388346.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/512#issuecomment-213070795>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
Looks good, closing design issue, implementation in #530
