### ISSUE TITLE
[versions] Identify bugs in current page versions implementation and create specific issues accordingly.

### ISSUE THREAD

**Issue by jth-** [punkave/apostrophe#517]

**Comment by boutell** [comment]
Actually, plaintext diff is working:

https://dl.dropboxusercontent.com/spa/jfyjetktfp495r1/-29s2wht.png

But some scenario presumably isn't. So please clarify how to bust it and reassign to me.

**Comment by mcoppola** [comment]
A current issue is that pieces don't seem to have versions of their own.  Only the parent index page.  The POST request for the `versions-editor` shows that the index page doc `_id` is supplied instead of the instance `_id`.  But in this regard, pieces instance versions is broken,

@boutell I see a note explaining "pieces subclasses add their own links to trigger the versions editor." but i'm not sure where this is implemented?

**Comment by boutell** [comment]
It's accessible through the edit modal. Maybe you're trying to do it in
context on the page? You guys would need to adjust that one too.

On Mon, Apr 25, 2016 at 11:04 AM, Matthew Coppola <notifications@github.com>
wrote:

> Reopened #517 <https://github.com/punkave/apostrophe/issues/517>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/517#event-640130563>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by mcoppola** [comment]
Ok gotcha.  That passes the correct instance `_id`.

However, I'm getting a 404 at `/modules/<piece_name>/versions-editor`.

**Comment by mcoppola** [comment]
A regular page's versions editor is also producing a 404 at 
`/modules/apostrophe-versions/versions-editor `.

An easy one to reproduce: 
-  Create a "Default" type page on Science Center.
-  Page Menu > Page Versions
-  Produces a 404 in the network panel

**Comment by boutell** [comment]
Page versions Work for me in the straw man project.

On Mon, Apr 25, 2016 at 11:32 AM, Matthew Coppola <notifications@github.com>
wrote:

> A regular page's versions editor is also producing a 404 at
> /modules/apostrophe-versions/versions-editor.
>
> An easy one to reproduce:
>
>    - Create a "Default" type page on Science Center.
>    - Page Menu > Page Versions
>    - Produces a 404 in the network panel
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/517#issuecomment-214397528>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
Created an issue accordingly for duplicate versions, closing this.
