### ISSUE TITLE
Best way to link to another page

### ISSUE THREAD

**Issue by janaobzerova** [punkave/apostrophe#523]
Hi,

I would like to make referencies to another page, I would like to have page type "animal", which will have information: name, original ID, new ID, mother and father. 

And now my question. :) When I will be creating new page, type Animal, I would like to have change to link Mother and Father field to existing pages. It is possible to have selectbox with all pages type animal? Or chance to link it together with tags? Or anything else?

Real example:
Existing page - title: "Arwen", slug: "arwen", newId: "FIN1256", oldId: "FIN/9874", mother, father:null
And when I create page - title: "Small Arwen" slug:"small-arwen",  newId: "FIN7766", oldId: null, and I would like to select somehow Arwen to mother field. (Every animal has title, slug, newId)

BTW: I do not know if it is Important, but I would like to see mother/father information in "Small Arwen" detail page in frontend.

Thanks for help!

**Comment by boutell** [comment]
I'm not sure if I understood every aspect of your question but you should
check out the apostrophe-fancy-page module and also learn about joins in
Apostrophe (see apostrophenow.org for documentation on this topic).

On Thu, Apr 21, 2016 at 11:10 AM, janaobzerova <notifications@github.com>
wrote:

> Hi,
>
> I would like to make referencies to another page, I would like to have
> page type "animal", which will have information: name, original ID, new ID,
> mother and father.
>
> And now my question. :) When I will be creating new page, type Animal, I
> would like to have change to link Mother and Father field to existing
> pages. It is possible to have selectbox with all pages type animal? Or
> chance to link it together with tags? Or anything else?
>
> Real example:
> Existing page - title: "Arwen", slug: "arwen", newId: "FIN1256", oldId:
> "FIN/9874", mother, father:null
> And when I create page - title: "Small Arwen" slug:"small-arwen", newId:
> "FIN7766", oldId: null, and I would like to select somehow Arwen to mother
> field.
>
> BTW: I do not know if it is Important, but I would like to see
> mother/father information in "Small Arwen" detail page in frontend.
>
> Thanks for help!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/523>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
