### ISSUE TITLE
[pages] Design an unpublished indicator for pages (and pieces) that also functions as a shortcut to a streamlined publishing process.

### ISSUE THREAD

**Issue by jth-** [punkave/apostrophe#524]

**Comment by stuartromanek** [comment]
<img width="1271" alt="screen shot 2016-04-21 at 4 01 23 pm" src="https://cloud.githubusercontent.com/assets/1889830/14722625/632dd98a-07da-11e6-9091-d641094be42e.png">
<img width="1266" alt="screen shot 2016-04-21 at 4 01 46 pm" src="https://cloud.githubusercontent.com/assets/1889830/14722626/632f8938-07da-11e6-9272-fdc88dadcce9.png">

**Comment by boutell** [comment]
My first thought is "very cool."

My second thought is "hmm, we're moving away from icons in favor of words,
so I'm surprised we would rely on an icon to address a potential cause of
confusion."

On Thu, Apr 21, 2016 at 4:02 PM, Stuart Romanek <notifications@github.com>
wrote:

> [image: screen shot 2016-04-21 at 4 01 23 pm]
> <https://cloud.githubusercontent.com/assets/1889830/14722625/632dd98a-07da-11e6-9091-d641094be42e.png>
> [image: screen shot 2016-04-21 at 4 01 46 pm]
> <https://cloud.githubusercontent.com/assets/1889830/14722626/632f8938-07da-11e6-9272-fdc88dadcce9.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/524#issuecomment-213092378>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by stuartromanek** [comment]
@boutell great point, icon came out of some iterations of combining the publish indicator/control into the actual Page Settings button, which ultimately felt weird. Also felt some ambiguity around the crossed out eye as a symbol. Now that it is a stand alone button I feel like it could just be labeled Unpublished and be floated next to the Page Settings menu.

Thanks for holding my hand to the fire.
