### ISSUE TITLE
[apostrophe-images] Manager checkbox don't always reflect the state of their inner, hidden, checkbox element.

### ISSUE THREAD

**Issue by jth-** [punkave/apostrophe#528]

**Comment by mcoppola** [comment]
I believe this is resolved with e72894d, but we could use some more test cases.

**Comment by boutell** [comment]
This is why DOM observers will someday be cool.

On Tue, Apr 26, 2016 at 1:35 PM, Matthew Coppola <notifications@github.com>
wrote:

> I believe this is resolved with e72894d
> <https://github.com/punkave/apostrophe/commit/e72894d6e727c8af7b918f410af49eb2d2c43dc3>,
> but we could use some more test cases.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/528#issuecomment-214822078>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
Merged #532
