### ISSUE TITLE
[manager] Double click on item opens two modals, and doesn't save the top one

### ISSUE THREAD

**Issue by mcoppola** [punkave/apostrophe#539]
Need to prevent double click from opening a second modal.

**Comment by boutell** [comment]
This will go away when we bring back the "busy" behavior. I suggest we just
port the 0.5 busy spinner for now, which is effective at solving this
mounting list of UX challenges (:

On Fri, Apr 29, 2016 at 3:30 PM, Matthew Coppola <notifications@github.com>
wrote:

> Need to prevent double click from opening a second modal.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/539>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
@mcoppola Could you verify that this is no longer occuring now that you implemented the global busy state? If so, we can close this.

**Comment by mcoppola** [comment]
confirmed!  this can be closed.
