### ISSUE TITLE
[versions] Duplicate versions are created when visiting a page with contextually edited content, i.e. areas.

### ISSUE THREAD

**Issue by jth-** [punkave/apostrophe#543]
This bug might be in the autosave logic of areas.

**Comment by jth-** [comment]
Closed in 54c439a

**Comment by boutell** [comment]
This broke editing rich text widgets after dragging them for three years. (: Fixing.

**Comment by boutell** [comment]
Probably dates back to a time when we didn't create a completely new object devoid of non-schema properties during sanitization. Back then it could have played out as described above.
