### ISSUE TITLE
[attachments] all/first helpers fail to recognize some valid items missing `type: attachment` property

### ISSUE THREAD

**Issue by mcoppola** [punkave/apostrophe#550]

**Comment by boutell** [comment]
There is a migration that fixes these, rub apostrophe-migrations:migrate

**Comment by jth-** [comment]
@boutell The migration works, we just weren't adding `type: 'attachment'` on new attachments. This commit seems to fix things: c4ac2e1c09498a6f519ce7014e4b474d95b628d4

**Comment by boutell** [comment]
Oh. Duh. Thanks.
