### ISSUE TITLE
[apostrophe-pages] Page order is not preserved when syncing a database.

### ISSUE THREAD

**Issue by jth-** [punkave/apostrophe#552]
The ordering of pages in the reorganize menu is subject to changing when syncing, for instance, from local to prod. My initial thoughts would be that, since Mongo doesn't seem to preserve natural order on sync, that something about are page ordering is falling back to natural order. I would imagine this shouldn't be the case, since it's nondeterministic, and that this should be entirely based upon page rank or something of that ilk.

**Comment by boutell** [comment]
Right, it should not be the case, it sounds like the "rank" property is not
being taken into account somehow by the descendants filter.

On Mon, May 16, 2016 at 9:31 AM, Jimmy Harrison <notifications@github.com>
wrote:

> The ordering of pages in the reorganize menu is subject to changing when
> syncing, for instance, from local to prod. My initial thoughts would be
> that, since Mongo doesn't seem to preserve natural order on sync, that
> something about are page ordering is falling back to natural order. I would
> imagine this shouldn't be the case, since it's nondeterministic, and that
> this should be entirely based upon page rank or something of that ilk.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/552>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
I've just determined that this is actually a case where I have two pages with the same level and rank, which I guess probably shouldn't happen?

**Comment by boutell** [comment]
It shouldn't. The only way it ought to be able to happen is in a race
condition where you created them simultaneously; that's a known issue (as
long as A2 has been around). If it's happening in any other circumstance,
the challenge is to figure out how to reproduce it.

We do need a fix for that race condition in the long run. Probably best to
resolve it through locking, but boo, locking.

At one point I thought it might be a silver bullet to add a random
fractional part to rank, but I think I came up with a scenario where it
didn't help.

On Tue, May 17, 2016 at 9:50 AM, Jimmy Harrison <notifications@github.com>
wrote:

> I've just determined that this is actually a case where I have two pages
> with the same level and rank, which I guess probably shouldn't happen?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/552#issuecomment-219723280>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
The PR I made earlier fixed the issue I was specifically producing here, so I'm going to close this issue for now.
