### ISSUE TITLE
[assets] req.browserCall should work with [data-apos-refreshable], apos.change should not duplicate apos.pageReady

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe#578]
browser-side js calls made with req.browserCall should work when refreshing apos-refreshable due to a change event. The apos.change method should rely on this mechanism invoking apos.pageReady rather than duplicating that logic. pageReady should be invoked via a wrapper that handles domready/next tick chores so it is easier to read.

**Comment by jth-** [comment]
Closed in #579
