### ISSUE TITLE
Rich text toolbar doesn't style or have icons in FF 47.0.1 (latest)

### ISSUE THREAD

**Issue by austinstarin** [punkave/apostrophe#609]

**Comment by boutell** [comment]
Good catch, is this in 0.5, 0.6 or both?

On Tue, Jul 12, 2016 at 7:15 AM, Austin Starin <notifications@github.com>
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/apostrophe/issues/609>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAB9fROnRU_oQvcccywCmq6grNm5bH5pks5qU3c8gaJpZM4JKSYC>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by austinstarin** [comment]
I'm only experiencing this in 0.6.

**Comment by boutell** [comment]
@stuartromanek this is beyond my CSS pay grade, please take a look? I hesitate to "npm publish" a CMS where you can't see the rich text editor toolbar in Firefox yet.

**Comment by boutell** [comment]
Edge 14 shows the buttons just fine and I found no problems bashing around the edit UI for a few minutes with it.

**Comment by boutell** [comment]
If I use the moono skin, it works fine in Firefox (change the skin setting in ckeditor's config.js):

https://dl.dropboxusercontent.com/spa/jfyjetktfp495r1/xjjn940a.png

General appearance of the moono skin:

https://dl.dropboxusercontent.com/spa/jfyjetktfp495r1/luthv66_.png

Versus the Apostrophe skin:

https://dl.dropboxusercontent.com/spa/jfyjetktfp495r1/-0nr8mes.png

Yeah OK I'll wait until we're able to figure this out, the loss of gorgeousness is unacceptable (:

**Comment by boutell** [comment]
I think you need to update editor_gecko.css for this to work.

**Comment by boutell** [comment]
HAHA I GOT IT YOU ARE OFF THE HOOK

Just had to explicitly configure the skin to say we don't give a shit about any platform specific CSS files, your standard styles look great in firefox

**Comment by boutell** [comment]
This is fixed, also I eliminated a superfluous copy of the theme.
