### ISSUE TITLE
Admin buttons block content areas

### ISSUE THREAD

**Issue by alexgleason** [punkave/apostrophe#647]
This is annoying if you're trying to click a particular element and the buttons get in the way, or if the button itself is taller than the content element and you get buttons overlaid on top of buttons... etc.

![screenshot from 2016-09-08 00 12 05](https://cloud.githubusercontent.com/assets/3639540/18336891/556478e4-7559-11e6-9cb3-5ac0f09e7820.png)

What's worse, the markup/styles don't make it simple to just hover the buttons to the right side. I realize that since this is happening on the front-end it will require some customization on each site to make things look perfect, but there has to be a better way. Could the buttons be outside of the hovered region?

![screenshot from 2016-09-08 00 12 44](https://cloud.githubusercontent.com/assets/3639540/18336904/7dc11928-7559-11e6-8603-e64d937deab2.png)

Here's an extreme example where I've added two empty fields. Note that it also happens on single line text fields though, which isn't such a fringe case.

**Comment by stuartromanek** [comment]
addressed in #720
