### ISSUE TITLE
Character limit on schema type string

### ISSUE THREAD

**Issue by austinstarin** [punkave/apostrophe#689]

**Comment by boutell** [comment]
I'm working on this one, as part of a bigger schemas update that will give us implicit definitions for some of the fussy join fields and a way to lint for bad configuration in general.

**Comment by agilbert** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Schema configuration updates](https://trello.com/c/dvK23TT3/5-schema-configuration-updates)
