### ISSUE TITLE
Area Widget Control UX overlap issue

### ISSUE THREAD

**Issue by geoffdimasi** [punkave/apostrophe#702]
When you add a 2 column content area, the controls overlap the "+" button used to add content:

https://www.dropbox.com/s/4x6qgkh922qbi82/Screenshot%202016-10-14%2015.22.51.png?dl=0

Figure out a way to have the controls and add content! :)

This is not an issue with other content types since you are usually adding content when you first add it.

**Comment by stuartromanek** [comment]
addressed in #1153
