### ISSUE TITLE
2.6.0 breaks array field JS

### ISSUE THREAD

**Issue by jonlong** [punkave/apostrophe#736]
I'm having an issue where the only solution I've found is rolling back to 2.5.1.

Widgets that feature `array` fields appear to have unresponsive chooser buttons in the Admin UI. Here's a quick look at what I'm seeing — this is a slideshow widget where each slide is added as an array item:

![image](http://g.recordit.co/iHsrCRoSGF.gif)

**Comment by stuartromanek** [comment]
also seeing this ... @boutell possible side effect of #723 ?

**Comment by boutell** [comment]
Taking a look.

**Comment by boutell** [comment]
Pull request for review in #737

**Comment by jonlong** [comment]
Confirmed that #737 fixes the issue for me. Thanks for the quick fix @boutell!
