### ISSUE TITLE
How do we deal with contact forms?

### ISSUE THREAD

**Issue by israelidanny** [punkave/apostrophe#74]
Or any other form / advanced logic page for that matter...

**Comment by benirose** [comment]
It sounds like this issue has been solved and I believe most of this has been documented on apostrophenow.org. Can we close this?

**Comment by boutell** [comment]
Has any of this been documented on apostrophenow.org? I don't see a
tutorial article in there on form handling. It would be easy enough to turn
my email into one.

On Fri, Feb 20, 2015 at 4:23 PM, benirose <notifications@github.com> wrote:

> It sounds like this issue has been solved and I believe most of this has
> been documented on apostrophenow.org. Can we close this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/74#issuecomment-75321603>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by benirose** [comment]
I'm pretty sure we have one for this:

"Write a HOWTO on fetching pages, snippets, etc. from Apostrophe with the help of apos.get and similar methods and also direct access to MongoDB collections other than apos.pages"

Not sure about the other two.

**Comment by boutell** [comment]
Haha, I'm responding to the original issue, it morphed into six others.

I'm closing this for being long and confusing at this point; we can reopen tickets if needed on specific topics.

**Comment by benirose** [comment]
:+1:
