### ISSUE TITLE
Use of nested areas and singletons is confusing, buggy

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe#742]
If you set "contextual: true" on an area or singleton schema field inside a widget, it can be edited on the page, and cannot be edited in a modal (the latter is relevant only if the widget is in a piece).

However if you fail to set "contextual: true" the editing interface still appears. It just doesn't save anything.

This is not well considered, figure it out.

**Comment by stuartromanek** [comment]
Decision on this is that if its possible to save, let the chrome work and save the changes.

If not, hide the widget chrome until better resolved.

**Comment by boutell** [comment]
This was fixed in #939. Areas can be edited contextually regardless of whether they have the contextual flag set. The contextual flag still has the role of suppressing inclusion of the field in the modal. That's optional, things can be edited both ways.
