### ISSUE TITLE
High severity vulnerability affecting this repo

### ISSUE THREAD

**Issue by benmag1** [punkave/apostrophe#749]
Hi there, 

We noticed that your repo has a high severity vulnerability: 
* [Remote Shell Command Injection](https://snyk.io/vuln/npm:gm:20151026?utm_source=gh_issue)
* Affected package: gm<=1.20.0

[Here is the test report for this repo](https://snyk.io/test/github/punkave/apostrophe?utm_source=gh_issue). 
If you’d like to fix this vulnerability, Snyk lets you generate a pull request that recommends the best upgrade path - there’s a link to fix this vulnerability on the test report. 

Stay secure :-)

Ben from the Snyk team

**Comment by boutell** [comment]
Hi Ben,

We don't call `compare` in `uploadfs` but I bumped up the dependency to get newer fixes anyway. Should clear your report.
