### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by warent** [punkave/apostrophe#750]
In http://apostrophecms.org/docs/tutorials/getting-started/custom-widgets.html
it says

```
First we need to create a folder for the module
mkdir -p lib/modules/link-widgets
````
And then right after:
```
Now we'll write the code for our module in lib/modules/custom-navigation-widgets/index.js
```

link-widgets vs custom-navigation-widgets. This inconsistency is confusing

**Comment by boutell** [comment]
Thanks, good eye. This is fixed.

Feel free to sign up for the developer directory: 

https://tomboutell1.typeform.com/to/NeqckD
