### ISSUE TITLE
Apostrophe should tell you if you upload an image too small for the current constraints

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe#751]
Right now you hit save and come back to the chooser and it says you have nothin'. This is super confusing and broken-feeling especially since we have constraints in the sandbox demo.

**Comment by stuartromanek** [comment]
This is closed, yeah? 

![image](https://user-images.githubusercontent.com/1889830/27227497-adfc3014-5271-11e7-9162-e3a5c7e52c89.png)
