### ISSUE TITLE
Reorganize and versions header finished button is cut off

### ISSUE THREAD

**Issue by austinstarin** [punkave/apostrophe#752]
cc @boutell @stuartromanek 

![reorganize-header](https://cloud.githubusercontent.com/assets/4621109/20527105/20b7b29c-b095-11e6-82b4-0f8678a4605f.png)

**Comment by austinstarin** [comment]
This is happening for versions as well cc/ @boutell @stuartromanek

**Comment by grdunn** [comment]
see https://github.com/punkave/apostrophe/pull/817 @austinstarin @stuartromanek
