### ISSUE TITLE
Cannot save text Areas inside Singletons.

### ISSUE THREAD

**Issue by stuartromanek** [punkave/apostrophe#81]
I have a singleton that is a Blog widget. That widget has Areas I would like to edit on the page. I get the appropriate Edit pencil and data-save attr but Apostrophe has no intention of saving it. Bummer

**Comment by boutell** [comment]
Did we fix this guys?

**Comment by boutell** [comment]
Fixed in 2.0, not happening for 0.5 if it hasn't
