### ISSUE TITLE
Forever Watch ?

### ISSUE THREAD

**Issue by daslicht** [punkave/apostrophe#811]
Hi,
I tried starting apostrophe using forever -w , but it keeps restarting due to file change.

I tried adding the data dir in a ```.foreverignore``` but that don't help.

Any ide how to make forever work please?
Or is there another way that you don't have to manually restart the server when changing something.

**Comment by fredrikekelund** [comment]
I haven't tried this extensively with Apostrophe, but what I would normally use for this type of restart-on-save functionality is [nodemon](https://www.npmjs.com/package/nodemon).

I tested with this command and it seemed to work well. The `-w` option tells nodemon what files/folders to watch, and the `-e` option which file extensions it should watch. 

```
nodemon -w app.js -w lib/modules -e js,html,css,less app.js
```

**Comment by daslicht** [comment]
Nice, that sounds promising, i ll try it later !

**Comment by fredrikekelund** [comment]
I can add that I have tried it more extensively by now, and it works great!
