### ISSUE TITLE
 Pages version & Reorganize are out of modal "overflow"

### ISSUE THREAD

**Issue by Mr0110** [punkave/apostrophe#821]
pages version -> finish button is out of modal :
![image](https://cloud.githubusercontent.com/assets/22819722/22805648/269093f4-eee4-11e6-9556-e544921e56b7.png)

also for reorganize modal:
![image](https://cloud.githubusercontent.com/assets/22819722/22805943/65507a72-eee5-11e6-841d-9ebd88a335bd.png)

.apos-ui.apos-modal .apos-modal-header .apos-modal-controls {
    position: relative;
    vertical-align: top;
    display: inline-block;
    _`/*max-width: 40%;*/`_
    float: right;
    white-space: nowrap;
    text-align: right;
}

![image](https://cloud.githubusercontent.com/assets/22819722/22806004/996ab1ec-eee5-11e6-9216-a8b163286257.png)

![image](https://cloud.githubusercontent.com/assets/22819722/22806028/bc5bfbc0-eee5-11e6-96dd-7ec239af2960.png)

![image](https://cloud.githubusercontent.com/assets/22819722/22806049/d31c65de-eee5-11e6-9d1a-83e3e0098d8d.png)

**Comment by austinstarin** [comment]
This was resolved 4cf877ff43ad62ef5ad03efecb0acc444309e377. Thanks!
