### ISSUE TITLE
Create a Bountysource team for Apostrophe

### ISSUE THREAD

**Issue by alexgleason** [punkave/apostrophe#827]
Lately I've been really interested in the idea of getting paid to work on open-source projects. Fortunately a service called [Bountysource](https://www.bountysource.com/) already solves a lot of this problem. Here's how it works:

1. You create a Bountysource team and authorize GitHub. These become integrated.
2. All GitHub issues become mirrored to Bountysource where people can pay money to place a bounty on an issue they want fixed.
3. Developers fix the issue, verify it with the team, then get paid the bounty.

This would benefit Apostrophe by increasing its engagement with a broader community. Receiving funds for fixing issues is more enticing to developers than the satisfaction of being altruistic. Part of me is still concerned about the consequences of bringing money into free software at all; will it encourage sabotaging behavior among developers rather than collaboration? But the appeal of being able to sustain oneself with free software outweighs my skepticism. As long as money is necessary to live, we should enable its ability to be obtained. The introduction of Bountysource now means that a child with an internet connection anywhere in the world can teach themselves programming using online resources and then use their skills to accrue money with little dependency on anything else.

Anyway, let me give an example of how an issue looks on Bountysource. Here's a popular issue for OwnCloud:

![screenshot from 2017-02-18 17 53 15](https://cloud.githubusercontent.com/assets/3639540/23097494/3f9394d4-f603-11e6-881b-0111c466c182.png)

As you can see, this issue has 30 backers. Quite a few different people care about this issue, so they've contributed money to up the ante in the hopes it will further entice someone to develop a solution.

![screenshot from 2017-02-18 17 53 42](https://cloud.githubusercontent.com/assets/3639540/23097500/60ad90f2-f603-11e6-89fb-3625f479e251.png)

Even if you don't plan to contribute money towards issues yourself, just having the Bountysource page allows other people to. So it's worth having either way, as long as someone will review the pull requests, which you are already doing. If you do want to engage the community, posting bounties on issues is a useful tool.

![screenshot from 2017-02-18 18 07 04](https://cloud.githubusercontent.com/assets/3639540/23097586/134fcf62-f605-11e6-898a-e28d07df2286.png)

There's also a feature that works like a little built-in mini Patreon. People who want to support the project can contribute a monthly dollar amount, which means Apostrophe can generate a passive income to delegate towards development.

You can read the full FAQ for Bountysource here: https://github.com/bountysource/core/wiki/Frequently-Asked-Questions

**Comment by stuartromanek** [comment]
Alright, we out there, looking lonely https://www.bountysource.com/teams/apostrophecms

We should maybe add this to our Community page in the marketing site redesign
