### ISSUE TITLE
Edits are being lost when a second logged-in user happens to be "just looking" at the page

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe#831]
There is an algorithm to detect when content has changed in the browser; content is only supposed to be saved if it is actually different from what was originally loaded.

This algorithm doesn't quite work in all cases. Sometimes it keeps detecting false positives, which generated zillions of page versions. In a bid to resolve this permanently, I added server-side logic to check whether the page has actually changed.

However, this doesn't solve the problem if user "A" is really editing and user "B" is just looking at the page.

User "B"'s area editor keeps trying to submit edits even though user "B" has done nothing. The server detects that these are real differences because user "A" has made changes. User "B" stomps user "A" even though they were never really editing. So sad.

(One variation of this sob story: user "A" might be trying to roll back page versions, and perceive that feature as broken because user "B"'s area editor keeps overruling them.)

One solution is to perfect the difference-detection algorithm in the browser. However we can also address the problem by not starting the "periodic area-saver" logic until user "B" actually touches the editing UI in some way, and resetting that flag after a save operation. This would be very good insurance against problems with the difference detection, and also make Apostrophe more efficient. A catch with that is being 100% sure we don't miss that some kind of contextual editing operation has occurred.

(Another option in principle is to introduce save buttons for areas and/or a hard switch between view and edit modes, with view mode being the default every time you open a page. I don't think we want to do that, it really cuts down on the contextual wow factor.)

More verification should be done that this is the root cause of certain issues impacting PL and other projects.

cc @agilbert @stuartromanek

**Comment by stuartromanek** [comment]
Is this issue officially solved with the 'take control' features?

**Comment by boutell** [comment]
Absolutely, and more specifically with the change to not even start trying to autosave areas until certain interactions take place.
