### ISSUE TITLE
Still too many situations where edits and/or version rollback can be thwarted by a second user

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe#840]
If user A and user B are both logged in with editing privileges, and user A is editing a page while user B is merely looking at it, user A's edits will keep getting stomped by user B, whose area editor logic will assume they are actively insisting the page stay the same.

While better difference detection on the browser side would help, there are reasons why that is a hard problem to get right 100% of the time, so the solution may also involve recognizing situations where user B is most likely editing vs. "just visiting."

Detecting this in a backwards compatible way is easy for some operations and potentially quite hard for others. For instance, it's not clear how to handle contextual editing functionality written by third parties that relies on the area autosaving mechanism, since it may not follow exactly the same pattern as our contextual rich text editor.

**Comment by newdesignideas** [comment]
WordPress solved this issue in a very rough manner: only one person can edit a single page at a time but another user can take over editing. It is rough, but it is quite clear and I having worked with novice editors, they do not mind that, because they understand what is going on. From it´s approach, I would suggest something like this:

- user A edits the page C
- user B visits the page C and gets a dark overlay and a notification with the options:
    - option x: take over editing from user A without saving their changes;
    - option y: view the page in a "passive mode". Essentially, on that page user B is as a logged out user;,
           -  the following is not implemented in WP, but maybe is a good idea: while on the page a notification appears if and when the page is ready for editing and the page reloads with saved edits from user A appearing;
   -  option z: cancel the operation.

Even if locking a page for editing and notifying when available for editing is a lot of work, it sounds better to give the editor an implicit choice on what they want to do, when they can do it and what will happen.

Perhaps, also, there would be slightly different lock down implementations for pieces versus pages.

**Comment by boutell** [comment]
## Conflict resolution between multiple editors

### UX considerations

What all this points to is that we need a reliable way to say "OK, this person is editing now," and also a reliable way to say "this person is not editing anymore." Those things are fundamental features that you can take for granted in a "back end" interface but have to build for yourself in a contextual interface.

And then we can move on to:

1. A notification: hey, Steve is editing this right now!

2. Blocking you unless you explicitly take over from Steve.

How might that work, from a UX perspective?

When I first come to a page... I am not editing.

If I manipulate the area controls, drag/drop widgets, or trigger the editor modal for a widget... I am now editing the doc that contains that area. 

If I click into a rich text widget, activating ckeditor... I am now editing the doc that contains that area.

However, in all of these cases, there should be an API call first to see if someone else is editing that doc, and if they are I should have to make a Wordpress-style "never mind / take over" decision at that point or my action should be cancelled.

Note I've been careful to write "the doc that contains that area" here. A web page can have several editable docs on it — pieces edited in context, the global doc, and the page.

An important question: when am I no longer editing a doc?

One answer is that I'm considered to be editing all of the docs where I've begun editing until I leave that webpage, or another user clicks the "take over editing" button, Wordpress-style. It's simple and it would be a reasonable first iteration.

A more nuanced answer might be that I'm no longer editing if I haven't done any of the above triggering actions or interacted with ckeditor for 5 minutes. The browser would voluntarily tell the server it's giving up control and close any contextual rich text editors. A nice touch might be that if I click on the rich text widget again ckeditor would jump scroll to where I had been.

If I take over editing, an apos-refresh should occur to make sure I'm starting where the last person left off.

### Alternative: the "I WANT TO START EDITING THIS PAGE NOW" button

We could have one. It does simplify some of the above. It would be disabled by default, but for clients who find collisions between editors frustrating it would be switched on.

I don't like it though. I'd rather move in the direction of robustly detecting when editing begins. 

### Alternative: actual concurrent editing

... Is a much harder problem. I think we should move ahead with a solution like the one above for 2.x.

### Implementation considerations

Tracking who is editing a doc is the basic challenge there.

Apostrophe's locks are for operations a single node request is trying to do exclusively. That's not enough for this purpose but we can use it as a building block:

1. Browser hits /modules/apostrophe-docs/editing, passes an id
2. Server gets a lock for that id
3. Server checks `doc.currentEditor`. If it's already set and it's not you, API response says "hey Bob has this now, bug off or tell me to take over". Else server sets `doc.currentEditor` to you
4. Server frees the lock

For a takeover, a "takeover: true" parameter is added, and in step 3 we're more forceful.

A problem with this scheme: how do takeovers actually work? How do we tell Bob that we're taking over from him, and how do we block Bob from further edits?

It's simpler than it looks: the /modules/apostrophe-areas/save-area route will also have to call claimCurrentEditorLock, which will contain the check described above.

This will add a little overhead, but it can't be helped if we're serious about maintaining support for contextual editing without an explicit "I WANT TO START EDITING THIS PAGE NOW" button.

**Comment by bobclewell** [comment]
Noting related issue: https://github.com/punkave/apostrophe/issues/958
