### ISSUE TITLE
Uploading new images fires client-side errors

### ISSUE THREAD

**Issue by zfalen** [punkave/apostrophe#870]
Working on a very simple implementation of Apostrophe, and noticed the following bug. 

Using the edit button on an `apostrophe-images` widget, then uploading a **new** media file gets me to **edit image** screen; however, **cannot save** the image, and the following error stack is printed to the console _NOTE: Refreshing the page and navigating back to the image selector reveals the new image did, in fact, upload... can select it as a replacement normally._

_CHROME 57:_
http://imgur.com/94Mpaf4

_FIREFOX 52:_
http://imgur.com/1SxNVR9

**This issue is happening in the normal image uploader, and the file uploader as well**

_Mac OSX 10.12.4_
_package.json:_
`{
  "name": "MFC-apostrophe",
  "version": "2.0.0",
  "description": "Minimal MFC-apostrophe",
  "main": "app.js",
  "scripts": {
    "start": "node app.js"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "P'unk Avenue",
  "license": "MIT",
  "dependencies": {
    "apostrophe": "^2.23.0"
  }
}
`

**Comment by stuartromanek** [comment]
Just tested, this has indeed been fixed, closing
