### ISSUE TITLE
How tu upgrade ckeditor version?

### ISSUE THREAD

**Issue by pablocruzpineda** [punkave/apostrophe#895]
I would like to use ckeditor 4.7 with the apostrophe-areas module, but currently it uses ckeditor 4.4. How can I upgrade ckeditor within apostrophe to use it? Thanks in advance. 
Pablo.

**Comment by stuartromanek** [comment]
Hey Pablo,
We recently upgrade apostrophe-areas to us CKEditor 4.6.2 if that helps you any.

I just made a more specific todo at #927 , The work would entail replacing CKEditor in the `apostrophe-areas` module. Peek in this commit for how we upgraded from 4.4.x https://github.com/punkave/apostrophe/pull/922/commits/9a16ef4adfff02665b6c81bcecb224a1e7a7b6f1

We would love a PR @pablocruzpineda !

Closing this for #927
