### ISSUE TITLE
Odd call to mongo.toArray, maybe a typo

### ISSUE THREAD

**Issue by nopnop** [punkave/apostrophe#902]
Hi,

This [call](https://github.com/punkave/apostrophe/blob/master/lib/modules/apostrophe-docs/lib/cursor.js#L1186) seem odd:

```
mongo.toArray(callback, function(err, results) { //..
```

Maybe the first argument of toArray is a typo, since `toArray()` takes only one callback argument ?

**Comment by jevillard** [comment]
Hi,

I tried to use ```explicitOrder``` filter in my app.
After read this issue, I removed the first argument of ```toArray()```, and the application no start...

**Comment by nopnop** [comment]
Yeah, in fact according to this [condition](https://github.com/punkave/apostrophe/blob/master/lib/modules/apostrophe-docs/lib/cursor.js#L1191), the callback is never called if there is no `explicitOrder` (thus, the async waterfall remain stuck).

**Comment by boutell** [comment]
PR #906 is in code review.

**Comment by boutell** [comment]
This fix was published.
