### ISSUE TITLE
Users should be able to conveniently edit the pieces they have chosen

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe#946]
Consider the user who works their way through various searches in the chooser/manager modal to pick 20 articles.

Now they want to edit the third one they picked.

It's right in front of them in the chooser (list at left), but they have to find it again in the manager (list at right) in order to edit it.

Fix this by introducing an edit pencil in the chooser.

**Comment by boutell** [comment]
See PR #947

**Comment by stuartromanek** [comment]
Can close this, yeah @boutell ?
