### ISSUE TITLE
Cannot login in after install

### ISSUE THREAD

**Issue by JGrimbert** [punkave/apostrophe#961]
Hello,

I installed apostrophe this morning.
Everything went fine, until the login page :(( 

I did the "node app.js apostrophe-users:add admin admin" ..
As it was not working I added a "adminPassword: 'SOMETHING'" in the app.js (seen here:https://www.npmjs.com/package/apostrophe-site)..

My mongo db seems normaly filled with an "admin" username and a  '{"hash":"eT5tguZo/SoRX9K9eKF44CK7K5XIaejrV8zWJmGfNkYaSrGMtaDVvGbT50iT3VRPtfP8RmlH9ixhVRSpLZo2Fg1I","salt":"SpKTRnzG77cTrFY91oniSdTUQUOU9HXLEIGy3BSGIonTlnu/lrg21Bym7ctz82wRkN8V+QKVgpy1OZRlcjOM3p7I","keyLength":66,"hashMethod":"pbkdf2","iterations":442850}' password hash.

I restarted the node sever, I created a new user (then restarted). Nothing works :( 

NB: After I try the "node app.js apostrophe-users:add admin admin, the cmd ask me a password like : 
"prompt: password:" (nothing is showing when I tipp it in the cmd) 

Did I do something wrong ?

**Comment by stuartromanek** [comment]
hi @JGrimbert 
The `apostrophe-users:add` task does not reveal the password it prompts you for as you type but it is indeed recording your input. You might have added a password to the admin user without realizing it.

To double check this try creating another user and give it a password
`node app.js apostrophe-users:add jgrimbert admin`

Try looking and posting on stackoverflow when getting started with the basic of Apostrophe https://stackoverflow.com/questions/tagged/apostrophe-cms

Thanks for trying us out!
