### ISSUE TITLE
documentation "Creating your own layout.html"

### ISSUE THREAD

**Issue by pixlab** [punkave/apostrophe#967]
I think there is an error in the documentation, this section:
`{# lib/modules/apostrophe-templates/views/layout.html in your project #}`

`{% extends data.outerLayout %}`

`{% block afterMain %}`
`  <footer>`
`    Copyright 2017, Remarkable Company`
`  </footer>`
`{% endblock %}`

layout.html should go into lib/modules/apostrophe-**pages**/views/ folder (not apostrophe-templates).....if I follow the documentation the console give me this error:
`Error: template not found: apostrophe-pages:layout.html`

thanks a lot
Roberto

**Comment by boutell** [comment]
Good catch. Will fix.

**Comment by boutell** [comment]
This is fixed. Keep the errata coming!
