### ISSUE TITLE
insert() and update() for pieces should give you the piece in the callback as a second argument

### ISSUE THREAD

**Issue by austinstarin** [punkave/apostrophe#971]
In a backwards compatible way `insert()` and `update()` for pieces should give you the piece in the callback as a second argument. This is especially helpful if you are using Promises.

**Comment by boutell** [comment]
PR in #996

**Comment by HollyPony** [comment]
It's a kind of related to a stackoverflow post : https://stackoverflow.com/questions/45302955/why-inserting-a-doc-result-to-an-array . It can be updated also :)

**Comment by boutell** [comment]
Yep once it is released

**Comment by boutell** [comment]
This was published.
