### ISSUE TITLE
apostrophe-pubmed and apostrophe-pubmed-import updates

### ISSUE THREAD

**Issue by bgantick** [punkave/apostrophe#975]

**Comment by boutell** [comment]
Is this a bug fix? An enhancement? Any movement (since it's been a while)?

**Comment by bgantick** [comment]
@boutell apostrophe-pubmed-import is broken - working on a fix

**Comment by bgantick** [comment]
No longer broken for large data sets - still working on enhancements to make it more useable. Issues opened in the module repo.
