### ISSUE TITLE
aposPrefix in loginBase.html

### ISSUE THREAD

**Issue by thecb4** [punkave/apostrophe#984]
I'm using nginx to proxy and leveraging the prefix capability in apostrophe. When working through the login, I kept getting an error that wasn't seeming to respect the apos.prefix I've set.

It looks like the apostrophe-login module loginBase.html is using an aposPrefix variable. 

`<form action="{% block action %}{{ aposPrefix }}/login{% endblock %}" method="post">`

Is this meant to be a separate variable that I need to set in the app.js in addition to the apos.prefix variable?

**Comment by boutell** [comment]
It's a bug! Left over from 0.5 and inadequately tested. Try
apostrophe.prefix? Pull request welcome.
